// Code generated by ent, DO NOT EDIT.

package blogcomment

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the blogcomment type in the database.
	Label = "blog_comment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBlogPostID holds the string denoting the blog_post_id field in the database.
	FieldBlogPostID = "blogPostId"
	// FieldParentID holds the string denoting the parent_id field in the database.
	FieldParentID = "parentId"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "displayName"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldReviewedByUserID holds the string denoting the reviewed_by_user_id field in the database.
	FieldReviewedByUserID = "reviewedByUserId"
	// FieldReviewedAt holds the string denoting the reviewed_at field in the database.
	FieldReviewedAt = "reviewedAt"
	// FieldIPHash holds the string denoting the ip_hash field in the database.
	FieldIPHash = "ipHash"
	// FieldFingerprint holds the string denoting the fingerprint field in the database.
	FieldFingerprint = "fingerprint"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "createdAt"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updatedAt"
	// EdgeChildren holds the string denoting the children edge name in mutations.
	EdgeChildren = "children"
	// EdgeBlogPost holds the string denoting the blog_post edge name in mutations.
	EdgeBlogPost = "blog_post"
	// EdgeParent holds the string denoting the parent edge name in mutations.
	EdgeParent = "parent"
	// EdgeReviewedBy holds the string denoting the reviewed_by edge name in mutations.
	EdgeReviewedBy = "reviewed_by"
	// Table holds the table name of the blogcomment in the database.
	Table = "blogComment"
	// ChildrenTable is the table that holds the children relation/edge.
	ChildrenTable = "blogComment"
	// ChildrenColumn is the table column denoting the children relation/edge.
	ChildrenColumn = "parentId"
	// BlogPostTable is the table that holds the blog_post relation/edge.
	BlogPostTable = "blogComment"
	// BlogPostInverseTable is the table name for the BlogPost entity.
	// It exists in this package in order to avoid circular dependency with the "blogpost" package.
	BlogPostInverseTable = "blogPost"
	// BlogPostColumn is the table column denoting the blog_post relation/edge.
	BlogPostColumn = "blogPostId"
	// ParentTable is the table that holds the parent relation/edge.
	ParentTable = "blogComment"
	// ParentColumn is the table column denoting the parent relation/edge.
	ParentColumn = "parentId"
	// ReviewedByTable is the table that holds the reviewed_by relation/edge.
	ReviewedByTable = "blogComment"
	// ReviewedByInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ReviewedByInverseTable = "user"
	// ReviewedByColumn is the table column denoting the reviewed_by relation/edge.
	ReviewedByColumn = "reviewedByUserId"
)

// Columns holds all SQL columns for blogcomment fields.
var Columns = []string{
	FieldID,
	FieldBlogPostID,
	FieldParentID,
	FieldDisplayName,
	FieldEmail,
	FieldBody,
	FieldStatus,
	FieldReviewedByUserID,
	FieldReviewedAt,
	FieldIPHash,
	FieldFingerprint,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// BlogPostIDValidator is a validator for the "blog_post_id" field. It is called by the builders before save.
	BlogPostIDValidator func(string) error
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// BodyValidator is a validator for the "body" field. It is called by the builders before save.
	BodyValidator func(string) error
	// IPHashValidator is a validator for the "ip_hash" field. It is called by the builders before save.
	IPHashValidator func(string) error
	// FingerprintValidator is a validator for the "fingerprint" field. It is called by the builders before save.
	FingerprintValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING is the default value of the Status enum.
const DefaultStatus = StatusPENDING

// Status values.
const (
	StatusPENDING  Status = "PENDING"
	StatusAPPROVED Status = "APPROVED"
	StatusREJECTED Status = "REJECTED"
	StatusSPAM     Status = "SPAM"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPENDING, StatusAPPROVED, StatusREJECTED, StatusSPAM:
		return nil
	default:
		return fmt.Errorf("blogcomment: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the BlogComment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBlogPostID orders the results by the blog_post_id field.
func ByBlogPostID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlogPostID, opts...).ToFunc()
}

// ByParentID orders the results by the parent_id field.
func ByParentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentID, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByBody orders the results by the body field.
func ByBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBody, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByReviewedByUserID orders the results by the reviewed_by_user_id field.
func ByReviewedByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewedByUserID, opts...).ToFunc()
}

// ByReviewedAt orders the results by the reviewed_at field.
func ByReviewedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewedAt, opts...).ToFunc()
}

// ByIPHash orders the results by the ip_hash field.
func ByIPHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIPHash, opts...).ToFunc()
}

// ByFingerprint orders the results by the fingerprint field.
func ByFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFingerprint, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByChildrenCount orders the results by children count.
func ByChildrenCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChildrenStep(), opts...)
	}
}

// ByChildren orders the results by children terms.
func ByChildren(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChildrenStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBlogPostField orders the results by blog_post field.
func ByBlogPostField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBlogPostStep(), sql.OrderByField(field, opts...))
	}
}

// ByParentField orders the results by parent field.
func ByParentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParentStep(), sql.OrderByField(field, opts...))
	}
}

// ByReviewedByField orders the results by reviewed_by field.
func ByReviewedByField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReviewedByStep(), sql.OrderByField(field, opts...))
	}
}
func newChildrenStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChildrenTable, ChildrenColumn),
	)
}
func newBlogPostStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BlogPostInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BlogPostTable, BlogPostColumn),
	)
}
func newParentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ParentTable, ParentColumn),
	)
}
func newReviewedByStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReviewedByInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ReviewedByTable, ReviewedByColumn),
	)
}
