// Code generated by ent, DO NOT EDIT.

package blogcomment

import (
	"api/internal/infrastructure/persistence/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldContainsFold(FieldID, id))
}

// BlogPostID applies equality check predicate on the "blog_post_id" field. It's identical to BlogPostIDEQ.
func BlogPostID(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldBlogPostID, v))
}

// ParentID applies equality check predicate on the "parent_id" field. It's identical to ParentIDEQ.
func ParentID(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldParentID, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldDisplayName, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldEmail, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldBody, v))
}

// ReviewedByUserID applies equality check predicate on the "reviewed_by_user_id" field. It's identical to ReviewedByUserIDEQ.
func ReviewedByUserID(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldReviewedByUserID, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldReviewedAt, v))
}

// IPHash applies equality check predicate on the "ip_hash" field. It's identical to IPHashEQ.
func IPHash(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldIPHash, v))
}

// Fingerprint applies equality check predicate on the "fingerprint" field. It's identical to FingerprintEQ.
func Fingerprint(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldFingerprint, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldUpdatedAt, v))
}

// BlogPostIDEQ applies the EQ predicate on the "blog_post_id" field.
func BlogPostIDEQ(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldBlogPostID, v))
}

// BlogPostIDNEQ applies the NEQ predicate on the "blog_post_id" field.
func BlogPostIDNEQ(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNEQ(FieldBlogPostID, v))
}

// BlogPostIDIn applies the In predicate on the "blog_post_id" field.
func BlogPostIDIn(vs ...string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldIn(FieldBlogPostID, vs...))
}

// BlogPostIDNotIn applies the NotIn predicate on the "blog_post_id" field.
func BlogPostIDNotIn(vs ...string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNotIn(FieldBlogPostID, vs...))
}

// BlogPostIDGT applies the GT predicate on the "blog_post_id" field.
func BlogPostIDGT(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGT(FieldBlogPostID, v))
}

// BlogPostIDGTE applies the GTE predicate on the "blog_post_id" field.
func BlogPostIDGTE(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGTE(FieldBlogPostID, v))
}

// BlogPostIDLT applies the LT predicate on the "blog_post_id" field.
func BlogPostIDLT(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLT(FieldBlogPostID, v))
}

// BlogPostIDLTE applies the LTE predicate on the "blog_post_id" field.
func BlogPostIDLTE(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLTE(FieldBlogPostID, v))
}

// BlogPostIDContains applies the Contains predicate on the "blog_post_id" field.
func BlogPostIDContains(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldContains(FieldBlogPostID, v))
}

// BlogPostIDHasPrefix applies the HasPrefix predicate on the "blog_post_id" field.
func BlogPostIDHasPrefix(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldHasPrefix(FieldBlogPostID, v))
}

// BlogPostIDHasSuffix applies the HasSuffix predicate on the "blog_post_id" field.
func BlogPostIDHasSuffix(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldHasSuffix(FieldBlogPostID, v))
}

// BlogPostIDEqualFold applies the EqualFold predicate on the "blog_post_id" field.
func BlogPostIDEqualFold(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEqualFold(FieldBlogPostID, v))
}

// BlogPostIDContainsFold applies the ContainsFold predicate on the "blog_post_id" field.
func BlogPostIDContainsFold(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldContainsFold(FieldBlogPostID, v))
}

// ParentIDEQ applies the EQ predicate on the "parent_id" field.
func ParentIDEQ(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldParentID, v))
}

// ParentIDNEQ applies the NEQ predicate on the "parent_id" field.
func ParentIDNEQ(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNEQ(FieldParentID, v))
}

// ParentIDIn applies the In predicate on the "parent_id" field.
func ParentIDIn(vs ...string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldIn(FieldParentID, vs...))
}

// ParentIDNotIn applies the NotIn predicate on the "parent_id" field.
func ParentIDNotIn(vs ...string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNotIn(FieldParentID, vs...))
}

// ParentIDGT applies the GT predicate on the "parent_id" field.
func ParentIDGT(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGT(FieldParentID, v))
}

// ParentIDGTE applies the GTE predicate on the "parent_id" field.
func ParentIDGTE(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGTE(FieldParentID, v))
}

// ParentIDLT applies the LT predicate on the "parent_id" field.
func ParentIDLT(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLT(FieldParentID, v))
}

// ParentIDLTE applies the LTE predicate on the "parent_id" field.
func ParentIDLTE(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLTE(FieldParentID, v))
}

// ParentIDContains applies the Contains predicate on the "parent_id" field.
func ParentIDContains(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldContains(FieldParentID, v))
}

// ParentIDHasPrefix applies the HasPrefix predicate on the "parent_id" field.
func ParentIDHasPrefix(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldHasPrefix(FieldParentID, v))
}

// ParentIDHasSuffix applies the HasSuffix predicate on the "parent_id" field.
func ParentIDHasSuffix(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldHasSuffix(FieldParentID, v))
}

// ParentIDIsNil applies the IsNil predicate on the "parent_id" field.
func ParentIDIsNil() predicate.BlogComment {
	return predicate.BlogComment(sql.FieldIsNull(FieldParentID))
}

// ParentIDNotNil applies the NotNil predicate on the "parent_id" field.
func ParentIDNotNil() predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNotNull(FieldParentID))
}

// ParentIDEqualFold applies the EqualFold predicate on the "parent_id" field.
func ParentIDEqualFold(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEqualFold(FieldParentID, v))
}

// ParentIDContainsFold applies the ContainsFold predicate on the "parent_id" field.
func ParentIDContainsFold(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldContainsFold(FieldParentID, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldContainsFold(FieldDisplayName, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldContainsFold(FieldEmail, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldContainsFold(FieldBody, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNotIn(FieldStatus, vs...))
}

// ReviewedByUserIDEQ applies the EQ predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDEQ(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldReviewedByUserID, v))
}

// ReviewedByUserIDNEQ applies the NEQ predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDNEQ(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNEQ(FieldReviewedByUserID, v))
}

// ReviewedByUserIDIn applies the In predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDIn(vs ...string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldIn(FieldReviewedByUserID, vs...))
}

// ReviewedByUserIDNotIn applies the NotIn predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDNotIn(vs ...string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNotIn(FieldReviewedByUserID, vs...))
}

// ReviewedByUserIDGT applies the GT predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDGT(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGT(FieldReviewedByUserID, v))
}

// ReviewedByUserIDGTE applies the GTE predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDGTE(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGTE(FieldReviewedByUserID, v))
}

// ReviewedByUserIDLT applies the LT predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDLT(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLT(FieldReviewedByUserID, v))
}

// ReviewedByUserIDLTE applies the LTE predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDLTE(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLTE(FieldReviewedByUserID, v))
}

// ReviewedByUserIDContains applies the Contains predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDContains(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldContains(FieldReviewedByUserID, v))
}

// ReviewedByUserIDHasPrefix applies the HasPrefix predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDHasPrefix(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldHasPrefix(FieldReviewedByUserID, v))
}

// ReviewedByUserIDHasSuffix applies the HasSuffix predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDHasSuffix(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldHasSuffix(FieldReviewedByUserID, v))
}

// ReviewedByUserIDIsNil applies the IsNil predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDIsNil() predicate.BlogComment {
	return predicate.BlogComment(sql.FieldIsNull(FieldReviewedByUserID))
}

// ReviewedByUserIDNotNil applies the NotNil predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDNotNil() predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNotNull(FieldReviewedByUserID))
}

// ReviewedByUserIDEqualFold applies the EqualFold predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDEqualFold(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEqualFold(FieldReviewedByUserID, v))
}

// ReviewedByUserIDContainsFold applies the ContainsFold predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDContainsFold(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldContainsFold(FieldReviewedByUserID, v))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLTE(FieldReviewedAt, v))
}

// ReviewedAtIsNil applies the IsNil predicate on the "reviewed_at" field.
func ReviewedAtIsNil() predicate.BlogComment {
	return predicate.BlogComment(sql.FieldIsNull(FieldReviewedAt))
}

// ReviewedAtNotNil applies the NotNil predicate on the "reviewed_at" field.
func ReviewedAtNotNil() predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNotNull(FieldReviewedAt))
}

// IPHashEQ applies the EQ predicate on the "ip_hash" field.
func IPHashEQ(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldIPHash, v))
}

// IPHashNEQ applies the NEQ predicate on the "ip_hash" field.
func IPHashNEQ(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNEQ(FieldIPHash, v))
}

// IPHashIn applies the In predicate on the "ip_hash" field.
func IPHashIn(vs ...string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldIn(FieldIPHash, vs...))
}

// IPHashNotIn applies the NotIn predicate on the "ip_hash" field.
func IPHashNotIn(vs ...string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNotIn(FieldIPHash, vs...))
}

// IPHashGT applies the GT predicate on the "ip_hash" field.
func IPHashGT(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGT(FieldIPHash, v))
}

// IPHashGTE applies the GTE predicate on the "ip_hash" field.
func IPHashGTE(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGTE(FieldIPHash, v))
}

// IPHashLT applies the LT predicate on the "ip_hash" field.
func IPHashLT(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLT(FieldIPHash, v))
}

// IPHashLTE applies the LTE predicate on the "ip_hash" field.
func IPHashLTE(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLTE(FieldIPHash, v))
}

// IPHashContains applies the Contains predicate on the "ip_hash" field.
func IPHashContains(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldContains(FieldIPHash, v))
}

// IPHashHasPrefix applies the HasPrefix predicate on the "ip_hash" field.
func IPHashHasPrefix(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldHasPrefix(FieldIPHash, v))
}

// IPHashHasSuffix applies the HasSuffix predicate on the "ip_hash" field.
func IPHashHasSuffix(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldHasSuffix(FieldIPHash, v))
}

// IPHashEqualFold applies the EqualFold predicate on the "ip_hash" field.
func IPHashEqualFold(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEqualFold(FieldIPHash, v))
}

// IPHashContainsFold applies the ContainsFold predicate on the "ip_hash" field.
func IPHashContainsFold(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldContainsFold(FieldIPHash, v))
}

// FingerprintEQ applies the EQ predicate on the "fingerprint" field.
func FingerprintEQ(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldFingerprint, v))
}

// FingerprintNEQ applies the NEQ predicate on the "fingerprint" field.
func FingerprintNEQ(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNEQ(FieldFingerprint, v))
}

// FingerprintIn applies the In predicate on the "fingerprint" field.
func FingerprintIn(vs ...string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldIn(FieldFingerprint, vs...))
}

// FingerprintNotIn applies the NotIn predicate on the "fingerprint" field.
func FingerprintNotIn(vs ...string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNotIn(FieldFingerprint, vs...))
}

// FingerprintGT applies the GT predicate on the "fingerprint" field.
func FingerprintGT(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGT(FieldFingerprint, v))
}

// FingerprintGTE applies the GTE predicate on the "fingerprint" field.
func FingerprintGTE(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGTE(FieldFingerprint, v))
}

// FingerprintLT applies the LT predicate on the "fingerprint" field.
func FingerprintLT(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLT(FieldFingerprint, v))
}

// FingerprintLTE applies the LTE predicate on the "fingerprint" field.
func FingerprintLTE(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLTE(FieldFingerprint, v))
}

// FingerprintContains applies the Contains predicate on the "fingerprint" field.
func FingerprintContains(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldContains(FieldFingerprint, v))
}

// FingerprintHasPrefix applies the HasPrefix predicate on the "fingerprint" field.
func FingerprintHasPrefix(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldHasPrefix(FieldFingerprint, v))
}

// FingerprintHasSuffix applies the HasSuffix predicate on the "fingerprint" field.
func FingerprintHasSuffix(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldHasSuffix(FieldFingerprint, v))
}

// FingerprintEqualFold applies the EqualFold predicate on the "fingerprint" field.
func FingerprintEqualFold(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEqualFold(FieldFingerprint, v))
}

// FingerprintContainsFold applies the ContainsFold predicate on the "fingerprint" field.
func FingerprintContainsFold(v string) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldContainsFold(FieldFingerprint, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BlogComment {
	return predicate.BlogComment(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasChildren applies the HasEdge predicate on the "children" edge.
func HasChildren() predicate.BlogComment {
	return predicate.BlogComment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChildrenTable, ChildrenColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChildrenWith applies the HasEdge predicate on the "children" edge with a given conditions (other predicates).
func HasChildrenWith(preds ...predicate.BlogComment) predicate.BlogComment {
	return predicate.BlogComment(func(s *sql.Selector) {
		step := newChildrenStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBlogPost applies the HasEdge predicate on the "blog_post" edge.
func HasBlogPost() predicate.BlogComment {
	return predicate.BlogComment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BlogPostTable, BlogPostColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBlogPostWith applies the HasEdge predicate on the "blog_post" edge with a given conditions (other predicates).
func HasBlogPostWith(preds ...predicate.BlogPost) predicate.BlogComment {
	return predicate.BlogComment(func(s *sql.Selector) {
		step := newBlogPostStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasParent applies the HasEdge predicate on the "parent" edge.
func HasParent() predicate.BlogComment {
	return predicate.BlogComment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ParentTable, ParentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentWith applies the HasEdge predicate on the "parent" edge with a given conditions (other predicates).
func HasParentWith(preds ...predicate.BlogComment) predicate.BlogComment {
	return predicate.BlogComment(func(s *sql.Selector) {
		step := newParentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReviewedBy applies the HasEdge predicate on the "reviewed_by" edge.
func HasReviewedBy() predicate.BlogComment {
	return predicate.BlogComment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReviewedByTable, ReviewedByColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReviewedByWith applies the HasEdge predicate on the "reviewed_by" edge with a given conditions (other predicates).
func HasReviewedByWith(preds ...predicate.User) predicate.BlogComment {
	return predicate.BlogComment(func(s *sql.Selector) {
		step := newReviewedByStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BlogComment) predicate.BlogComment {
	return predicate.BlogComment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BlogComment) predicate.BlogComment {
	return predicate.BlogComment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BlogComment) predicate.BlogComment {
	return predicate.BlogComment(sql.NotPredicates(p))
}
