// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/infrastructure/persistence/ent/blogcomment"
	"api/internal/infrastructure/persistence/ent/blogpost"
	"api/internal/infrastructure/persistence/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// BlogComment is the model entity for the BlogComment schema.
type BlogComment struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// BlogPostID holds the value of the "blog_post_id" field.
	BlogPostID string `json:"blog_post_id,omitempty"`
	// ParentID holds the value of the "parent_id" field.
	ParentID *string `json:"parent_id,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Body holds the value of the "body" field.
	Body string `json:"body,omitempty"`
	// Status holds the value of the "status" field.
	Status blogcomment.Status `json:"status,omitempty"`
	// ReviewedByUserID holds the value of the "reviewed_by_user_id" field.
	ReviewedByUserID *string `json:"reviewed_by_user_id,omitempty"`
	// ReviewedAt holds the value of the "reviewed_at" field.
	ReviewedAt *time.Time `json:"reviewed_at,omitempty"`
	// IPHash holds the value of the "ip_hash" field.
	IPHash string `json:"ip_hash,omitempty"`
	// Fingerprint holds the value of the "fingerprint" field.
	Fingerprint string `json:"fingerprint,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BlogCommentQuery when eager-loading is set.
	Edges        BlogCommentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BlogCommentEdges holds the relations/edges for other nodes in the graph.
type BlogCommentEdges struct {
	// Children holds the value of the children edge.
	Children []*BlogComment `json:"children,omitempty"`
	// BlogPost holds the value of the blog_post edge.
	BlogPost *BlogPost `json:"blog_post,omitempty"`
	// Parent holds the value of the parent edge.
	Parent *BlogComment `json:"parent,omitempty"`
	// ReviewedBy holds the value of the reviewed_by edge.
	ReviewedBy *User `json:"reviewed_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e BlogCommentEdges) ChildrenOrErr() ([]*BlogComment, error) {
	if e.loadedTypes[0] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// BlogPostOrErr returns the BlogPost value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BlogCommentEdges) BlogPostOrErr() (*BlogPost, error) {
	if e.BlogPost != nil {
		return e.BlogPost, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: blogpost.Label}
	}
	return nil, &NotLoadedError{edge: "blog_post"}
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BlogCommentEdges) ParentOrErr() (*BlogComment, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: blogcomment.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ReviewedByOrErr returns the ReviewedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BlogCommentEdges) ReviewedByOrErr() (*User, error) {
	if e.ReviewedBy != nil {
		return e.ReviewedBy, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "reviewed_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BlogComment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case blogcomment.FieldID, blogcomment.FieldBlogPostID, blogcomment.FieldParentID, blogcomment.FieldDisplayName, blogcomment.FieldEmail, blogcomment.FieldBody, blogcomment.FieldStatus, blogcomment.FieldReviewedByUserID, blogcomment.FieldIPHash, blogcomment.FieldFingerprint:
			values[i] = new(sql.NullString)
		case blogcomment.FieldReviewedAt, blogcomment.FieldCreatedAt, blogcomment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BlogComment fields.
func (_m *BlogComment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case blogcomment.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case blogcomment.FieldBlogPostID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field blog_post_id", values[i])
			} else if value.Valid {
				_m.BlogPostID = value.String
			}
		case blogcomment.FieldParentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = new(string)
				*_m.ParentID = value.String
			}
		case blogcomment.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case blogcomment.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case blogcomment.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				_m.Body = value.String
			}
		case blogcomment.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = blogcomment.Status(value.String)
			}
		case blogcomment.FieldReviewedByUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_by_user_id", values[i])
			} else if value.Valid {
				_m.ReviewedByUserID = new(string)
				*_m.ReviewedByUserID = value.String
			}
		case blogcomment.FieldReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_at", values[i])
			} else if value.Valid {
				_m.ReviewedAt = new(time.Time)
				*_m.ReviewedAt = value.Time
			}
		case blogcomment.FieldIPHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_hash", values[i])
			} else if value.Valid {
				_m.IPHash = value.String
			}
		case blogcomment.FieldFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fingerprint", values[i])
			} else if value.Valid {
				_m.Fingerprint = value.String
			}
		case blogcomment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case blogcomment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BlogComment.
// This includes values selected through modifiers, order, etc.
func (_m *BlogComment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChildren queries the "children" edge of the BlogComment entity.
func (_m *BlogComment) QueryChildren() *BlogCommentQuery {
	return NewBlogCommentClient(_m.config).QueryChildren(_m)
}

// QueryBlogPost queries the "blog_post" edge of the BlogComment entity.
func (_m *BlogComment) QueryBlogPost() *BlogPostQuery {
	return NewBlogCommentClient(_m.config).QueryBlogPost(_m)
}

// QueryParent queries the "parent" edge of the BlogComment entity.
func (_m *BlogComment) QueryParent() *BlogCommentQuery {
	return NewBlogCommentClient(_m.config).QueryParent(_m)
}

// QueryReviewedBy queries the "reviewed_by" edge of the BlogComment entity.
func (_m *BlogComment) QueryReviewedBy() *UserQuery {
	return NewBlogCommentClient(_m.config).QueryReviewedBy(_m)
}

// Update returns a builder for updating this BlogComment.
// Note that you need to call BlogComment.Unwrap() before calling this method if this BlogComment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BlogComment) Update() *BlogCommentUpdateOne {
	return NewBlogCommentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BlogComment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BlogComment) Unwrap() *BlogComment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BlogComment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BlogComment) String() string {
	var builder strings.Builder
	builder.WriteString("BlogComment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("blog_post_id=")
	builder.WriteString(_m.BlogPostID)
	builder.WriteString(", ")
	if v := _m.ParentID; v != nil {
		builder.WriteString("parent_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(_m.Body)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.ReviewedByUserID; v != nil {
		builder.WriteString("reviewed_by_user_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ReviewedAt; v != nil {
		builder.WriteString("reviewed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("ip_hash=")
	builder.WriteString(_m.IPHash)
	builder.WriteString(", ")
	builder.WriteString("fingerprint=")
	builder.WriteString(_m.Fingerprint)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BlogComments is a parsable slice of BlogComment.
type BlogComments []*BlogComment
