// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/infrastructure/persistence/ent/blogcomment"
	"api/internal/infrastructure/persistence/ent/blogpost"
	"api/internal/infrastructure/persistence/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BlogPostCreate is the builder for creating a BlogPost entity.
type BlogPostCreate struct {
	config
	mutation *BlogPostMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *BlogPostCreate) SetTitle(v string) *BlogPostCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *BlogPostCreate) SetSlug(v string) *BlogPostCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetExcerpt sets the "excerpt" field.
func (_c *BlogPostCreate) SetExcerpt(v string) *BlogPostCreate {
	_c.mutation.SetExcerpt(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *BlogPostCreate) SetContent(v string) *BlogPostCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetTags sets the "tags" field.
func (_c *BlogPostCreate) SetTags(v []string) *BlogPostCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *BlogPostCreate) SetCategory(v string) *BlogPostCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetCoverImagePlaceholder sets the "cover_image_placeholder" field.
func (_c *BlogPostCreate) SetCoverImagePlaceholder(v string) *BlogPostCreate {
	_c.mutation.SetCoverImagePlaceholder(v)
	return _c
}

// SetNillableCoverImagePlaceholder sets the "cover_image_placeholder" field if the given value is not nil.
func (_c *BlogPostCreate) SetNillableCoverImagePlaceholder(v *string) *BlogPostCreate {
	if v != nil {
		_c.SetCoverImagePlaceholder(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *BlogPostCreate) SetStatus(v blogpost.Status) *BlogPostCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BlogPostCreate) SetNillableStatus(v *blogpost.Status) *BlogPostCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetFeatured sets the "featured" field.
func (_c *BlogPostCreate) SetFeatured(v bool) *BlogPostCreate {
	_c.mutation.SetFeatured(v)
	return _c
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_c *BlogPostCreate) SetNillableFeatured(v *bool) *BlogPostCreate {
	if v != nil {
		_c.SetFeatured(*v)
	}
	return _c
}

// SetPublishDate sets the "publish_date" field.
func (_c *BlogPostCreate) SetPublishDate(v time.Time) *BlogPostCreate {
	_c.mutation.SetPublishDate(v)
	return _c
}

// SetNillablePublishDate sets the "publish_date" field if the given value is not nil.
func (_c *BlogPostCreate) SetNillablePublishDate(v *time.Time) *BlogPostCreate {
	if v != nil {
		_c.SetPublishDate(*v)
	}
	return _c
}

// SetReadingTime sets the "reading_time" field.
func (_c *BlogPostCreate) SetReadingTime(v string) *BlogPostCreate {
	_c.mutation.SetReadingTime(v)
	return _c
}

// SetSeoTitle sets the "seo_title" field.
func (_c *BlogPostCreate) SetSeoTitle(v string) *BlogPostCreate {
	_c.mutation.SetSeoTitle(v)
	return _c
}

// SetNillableSeoTitle sets the "seo_title" field if the given value is not nil.
func (_c *BlogPostCreate) SetNillableSeoTitle(v *string) *BlogPostCreate {
	if v != nil {
		_c.SetSeoTitle(*v)
	}
	return _c
}

// SetSeoDescription sets the "seo_description" field.
func (_c *BlogPostCreate) SetSeoDescription(v string) *BlogPostCreate {
	_c.mutation.SetSeoDescription(v)
	return _c
}

// SetNillableSeoDescription sets the "seo_description" field if the given value is not nil.
func (_c *BlogPostCreate) SetNillableSeoDescription(v *string) *BlogPostCreate {
	if v != nil {
		_c.SetSeoDescription(*v)
	}
	return _c
}

// SetAuthorName sets the "author_name" field.
func (_c *BlogPostCreate) SetAuthorName(v string) *BlogPostCreate {
	_c.mutation.SetAuthorName(v)
	return _c
}

// SetAuthorUserID sets the "author_user_id" field.
func (_c *BlogPostCreate) SetAuthorUserID(v string) *BlogPostCreate {
	_c.mutation.SetAuthorUserID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BlogPostCreate) SetCreatedAt(v time.Time) *BlogPostCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BlogPostCreate) SetNillableCreatedAt(v *time.Time) *BlogPostCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BlogPostCreate) SetUpdatedAt(v time.Time) *BlogPostCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *BlogPostCreate) SetID(v string) *BlogPostCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddCommentIDs adds the "comments" edge to the BlogComment entity by IDs.
func (_c *BlogPostCreate) AddCommentIDs(ids ...string) *BlogPostCreate {
	_c.mutation.AddCommentIDs(ids...)
	return _c
}

// AddComments adds the "comments" edges to the BlogComment entity.
func (_c *BlogPostCreate) AddComments(v ...*BlogComment) *BlogPostCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCommentIDs(ids...)
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_c *BlogPostCreate) SetAuthorID(id string) *BlogPostCreate {
	_c.mutation.SetAuthorID(id)
	return _c
}

// SetAuthor sets the "author" edge to the User entity.
func (_c *BlogPostCreate) SetAuthor(v *User) *BlogPostCreate {
	return _c.SetAuthorID(v.ID)
}

// Mutation returns the BlogPostMutation object of the builder.
func (_c *BlogPostCreate) Mutation() *BlogPostMutation {
	return _c.mutation
}

// Save creates the BlogPost in the database.
func (_c *BlogPostCreate) Save(ctx context.Context) (*BlogPost, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BlogPostCreate) SaveX(ctx context.Context) *BlogPost {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BlogPostCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BlogPostCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BlogPostCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := blogpost.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Featured(); !ok {
		v := blogpost.DefaultFeatured
		_c.mutation.SetFeatured(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := blogpost.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BlogPostCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "BlogPost.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := blogpost.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "BlogPost.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "BlogPost.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := blogpost.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "BlogPost.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Excerpt(); !ok {
		return &ValidationError{Name: "excerpt", err: errors.New(`ent: missing required field "BlogPost.excerpt"`)}
	}
	if v, ok := _c.mutation.Excerpt(); ok {
		if err := blogpost.ExcerptValidator(v); err != nil {
			return &ValidationError{Name: "excerpt", err: fmt.Errorf(`ent: validator failed for field "BlogPost.excerpt": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "BlogPost.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := blogpost.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "BlogPost.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "BlogPost.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := blogpost.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "BlogPost.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "BlogPost.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := blogpost.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BlogPost.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Featured(); !ok {
		return &ValidationError{Name: "featured", err: errors.New(`ent: missing required field "BlogPost.featured"`)}
	}
	if _, ok := _c.mutation.ReadingTime(); !ok {
		return &ValidationError{Name: "reading_time", err: errors.New(`ent: missing required field "BlogPost.reading_time"`)}
	}
	if v, ok := _c.mutation.ReadingTime(); ok {
		if err := blogpost.ReadingTimeValidator(v); err != nil {
			return &ValidationError{Name: "reading_time", err: fmt.Errorf(`ent: validator failed for field "BlogPost.reading_time": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthorName(); !ok {
		return &ValidationError{Name: "author_name", err: errors.New(`ent: missing required field "BlogPost.author_name"`)}
	}
	if v, ok := _c.mutation.AuthorName(); ok {
		if err := blogpost.AuthorNameValidator(v); err != nil {
			return &ValidationError{Name: "author_name", err: fmt.Errorf(`ent: validator failed for field "BlogPost.author_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthorUserID(); !ok {
		return &ValidationError{Name: "author_user_id", err: errors.New(`ent: missing required field "BlogPost.author_user_id"`)}
	}
	if v, ok := _c.mutation.AuthorUserID(); ok {
		if err := blogpost.AuthorUserIDValidator(v); err != nil {
			return &ValidationError{Name: "author_user_id", err: fmt.Errorf(`ent: validator failed for field "BlogPost.author_user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BlogPost.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BlogPost.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := blogpost.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "BlogPost.id": %w`, err)}
		}
	}
	if len(_c.mutation.AuthorIDs()) == 0 {
		return &ValidationError{Name: "author", err: errors.New(`ent: missing required edge "BlogPost.author"`)}
	}
	return nil
}

func (_c *BlogPostCreate) sqlSave(ctx context.Context) (*BlogPost, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected BlogPost.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BlogPostCreate) createSpec() (*BlogPost, *sqlgraph.CreateSpec) {
	var (
		_node = &BlogPost{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(blogpost.Table, sqlgraph.NewFieldSpec(blogpost.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(blogpost.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(blogpost.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Excerpt(); ok {
		_spec.SetField(blogpost.FieldExcerpt, field.TypeString, value)
		_node.Excerpt = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(blogpost.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(blogpost.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(blogpost.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.CoverImagePlaceholder(); ok {
		_spec.SetField(blogpost.FieldCoverImagePlaceholder, field.TypeString, value)
		_node.CoverImagePlaceholder = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(blogpost.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Featured(); ok {
		_spec.SetField(blogpost.FieldFeatured, field.TypeBool, value)
		_node.Featured = value
	}
	if value, ok := _c.mutation.PublishDate(); ok {
		_spec.SetField(blogpost.FieldPublishDate, field.TypeTime, value)
		_node.PublishDate = &value
	}
	if value, ok := _c.mutation.ReadingTime(); ok {
		_spec.SetField(blogpost.FieldReadingTime, field.TypeString, value)
		_node.ReadingTime = value
	}
	if value, ok := _c.mutation.SeoTitle(); ok {
		_spec.SetField(blogpost.FieldSeoTitle, field.TypeString, value)
		_node.SeoTitle = &value
	}
	if value, ok := _c.mutation.SeoDescription(); ok {
		_spec.SetField(blogpost.FieldSeoDescription, field.TypeString, value)
		_node.SeoDescription = &value
	}
	if value, ok := _c.mutation.AuthorName(); ok {
		_spec.SetField(blogpost.FieldAuthorName, field.TypeString, value)
		_node.AuthorName = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(blogpost.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(blogpost.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   blogpost.CommentsTable,
			Columns: []string{blogpost.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blogcomment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   blogpost.AuthorTable,
			Columns: []string{blogpost.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AuthorUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BlogPostCreateBulk is the builder for creating many BlogPost entities in bulk.
type BlogPostCreateBulk struct {
	config
	err      error
	builders []*BlogPostCreate
}

// Save creates the BlogPost entities in the database.
func (_c *BlogPostCreateBulk) Save(ctx context.Context) ([]*BlogPost, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BlogPost, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BlogPostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BlogPostCreateBulk) SaveX(ctx context.Context) []*BlogPost {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BlogPostCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BlogPostCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
