// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/infrastructure/persistence/ent/certificate"
	"api/internal/infrastructure/persistence/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CertificateUpdate is the builder for updating Certificate entities.
type CertificateUpdate struct {
	config
	hooks    []Hook
	mutation *CertificateMutation
}

// Where appends a list predicates to the CertificateUpdate builder.
func (_u *CertificateUpdate) Where(ps ...predicate.Certificate) *CertificateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CertificateUpdate) SetName(v string) *CertificateUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableName(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIssuer sets the "issuer" field.
func (_u *CertificateUpdate) SetIssuer(v string) *CertificateUpdate {
	_u.mutation.SetIssuer(v)
	return _u
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableIssuer(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetIssuer(*v)
	}
	return _u
}

// SetYear sets the "year" field.
func (_u *CertificateUpdate) SetYear(v string) *CertificateUpdate {
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableYear(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// SetVerificationLink sets the "verification_link" field.
func (_u *CertificateUpdate) SetVerificationLink(v string) *CertificateUpdate {
	_u.mutation.SetVerificationLink(v)
	return _u
}

// SetNillableVerificationLink sets the "verification_link" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableVerificationLink(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetVerificationLink(*v)
	}
	return _u
}

// SetCredentialID sets the "credential_id" field.
func (_u *CertificateUpdate) SetCredentialID(v string) *CertificateUpdate {
	_u.mutation.SetCredentialID(v)
	return _u
}

// SetNillableCredentialID sets the "credential_id" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableCredentialID(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetCredentialID(*v)
	}
	return _u
}

// ClearCredentialID clears the value of the "credential_id" field.
func (_u *CertificateUpdate) ClearCredentialID() *CertificateUpdate {
	_u.mutation.ClearCredentialID()
	return _u
}

// SetFeatured sets the "featured" field.
func (_u *CertificateUpdate) SetFeatured(v bool) *CertificateUpdate {
	_u.mutation.SetFeatured(v)
	return _u
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableFeatured(v *bool) *CertificateUpdate {
	if v != nil {
		_u.SetFeatured(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *CertificateUpdate) SetSortOrder(v int) *CertificateUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableSortOrder(v *int) *CertificateUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *CertificateUpdate) AddSortOrder(v int) *CertificateUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CertificateUpdate) SetCreatedAt(v time.Time) *CertificateUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableCreatedAt(v *time.Time) *CertificateUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CertificateUpdate) SetUpdatedAt(v time.Time) *CertificateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CertificateMutation object of the builder.
func (_u *CertificateUpdate) Mutation() *CertificateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CertificateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CertificateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CertificateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CertificateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CertificateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := certificate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CertificateUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := certificate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Certificate.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Issuer(); ok {
		if err := certificate.IssuerValidator(v); err != nil {
			return &ValidationError{Name: "issuer", err: fmt.Errorf(`ent: validator failed for field "Certificate.issuer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Year(); ok {
		if err := certificate.YearValidator(v); err != nil {
			return &ValidationError{Name: "year", err: fmt.Errorf(`ent: validator failed for field "Certificate.year": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VerificationLink(); ok {
		if err := certificate.VerificationLinkValidator(v); err != nil {
			return &ValidationError{Name: "verification_link", err: fmt.Errorf(`ent: validator failed for field "Certificate.verification_link": %w`, err)}
		}
	}
	return nil
}

func (_u *CertificateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(certificate.Table, certificate.Columns, sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(certificate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Issuer(); ok {
		_spec.SetField(certificate.FieldIssuer, field.TypeString, value)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(certificate.FieldYear, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerificationLink(); ok {
		_spec.SetField(certificate.FieldVerificationLink, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialID(); ok {
		_spec.SetField(certificate.FieldCredentialID, field.TypeString, value)
	}
	if _u.mutation.CredentialIDCleared() {
		_spec.ClearField(certificate.FieldCredentialID, field.TypeString)
	}
	if value, ok := _u.mutation.Featured(); ok {
		_spec.SetField(certificate.FieldFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(certificate.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(certificate.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(certificate.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(certificate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{certificate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CertificateUpdateOne is the builder for updating a single Certificate entity.
type CertificateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CertificateMutation
}

// SetName sets the "name" field.
func (_u *CertificateUpdateOne) SetName(v string) *CertificateUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableName(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIssuer sets the "issuer" field.
func (_u *CertificateUpdateOne) SetIssuer(v string) *CertificateUpdateOne {
	_u.mutation.SetIssuer(v)
	return _u
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableIssuer(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetIssuer(*v)
	}
	return _u
}

// SetYear sets the "year" field.
func (_u *CertificateUpdateOne) SetYear(v string) *CertificateUpdateOne {
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableYear(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// SetVerificationLink sets the "verification_link" field.
func (_u *CertificateUpdateOne) SetVerificationLink(v string) *CertificateUpdateOne {
	_u.mutation.SetVerificationLink(v)
	return _u
}

// SetNillableVerificationLink sets the "verification_link" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableVerificationLink(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetVerificationLink(*v)
	}
	return _u
}

// SetCredentialID sets the "credential_id" field.
func (_u *CertificateUpdateOne) SetCredentialID(v string) *CertificateUpdateOne {
	_u.mutation.SetCredentialID(v)
	return _u
}

// SetNillableCredentialID sets the "credential_id" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableCredentialID(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetCredentialID(*v)
	}
	return _u
}

// ClearCredentialID clears the value of the "credential_id" field.
func (_u *CertificateUpdateOne) ClearCredentialID() *CertificateUpdateOne {
	_u.mutation.ClearCredentialID()
	return _u
}

// SetFeatured sets the "featured" field.
func (_u *CertificateUpdateOne) SetFeatured(v bool) *CertificateUpdateOne {
	_u.mutation.SetFeatured(v)
	return _u
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableFeatured(v *bool) *CertificateUpdateOne {
	if v != nil {
		_u.SetFeatured(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *CertificateUpdateOne) SetSortOrder(v int) *CertificateUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableSortOrder(v *int) *CertificateUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *CertificateUpdateOne) AddSortOrder(v int) *CertificateUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CertificateUpdateOne) SetCreatedAt(v time.Time) *CertificateUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableCreatedAt(v *time.Time) *CertificateUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CertificateUpdateOne) SetUpdatedAt(v time.Time) *CertificateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CertificateMutation object of the builder.
func (_u *CertificateUpdateOne) Mutation() *CertificateMutation {
	return _u.mutation
}

// Where appends a list predicates to the CertificateUpdate builder.
func (_u *CertificateUpdateOne) Where(ps ...predicate.Certificate) *CertificateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CertificateUpdateOne) Select(field string, fields ...string) *CertificateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Certificate entity.
func (_u *CertificateUpdateOne) Save(ctx context.Context) (*Certificate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CertificateUpdateOne) SaveX(ctx context.Context) *Certificate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CertificateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CertificateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CertificateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := certificate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CertificateUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := certificate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Certificate.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Issuer(); ok {
		if err := certificate.IssuerValidator(v); err != nil {
			return &ValidationError{Name: "issuer", err: fmt.Errorf(`ent: validator failed for field "Certificate.issuer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Year(); ok {
		if err := certificate.YearValidator(v); err != nil {
			return &ValidationError{Name: "year", err: fmt.Errorf(`ent: validator failed for field "Certificate.year": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VerificationLink(); ok {
		if err := certificate.VerificationLinkValidator(v); err != nil {
			return &ValidationError{Name: "verification_link", err: fmt.Errorf(`ent: validator failed for field "Certificate.verification_link": %w`, err)}
		}
	}
	return nil
}

func (_u *CertificateUpdateOne) sqlSave(ctx context.Context) (_node *Certificate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(certificate.Table, certificate.Columns, sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Certificate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, certificate.FieldID)
		for _, f := range fields {
			if !certificate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != certificate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(certificate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Issuer(); ok {
		_spec.SetField(certificate.FieldIssuer, field.TypeString, value)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(certificate.FieldYear, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerificationLink(); ok {
		_spec.SetField(certificate.FieldVerificationLink, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialID(); ok {
		_spec.SetField(certificate.FieldCredentialID, field.TypeString, value)
	}
	if _u.mutation.CredentialIDCleared() {
		_spec.ClearField(certificate.FieldCredentialID, field.TypeString)
	}
	if value, ok := _u.mutation.Featured(); ok {
		_spec.SetField(certificate.FieldFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(certificate.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(certificate.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(certificate.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(certificate.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Certificate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{certificate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
