// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/infrastructure/persistence/ent/certificate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CertificateCreate is the builder for creating a Certificate entity.
type CertificateCreate struct {
	config
	mutation *CertificateMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *CertificateCreate) SetName(v string) *CertificateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetIssuer sets the "issuer" field.
func (_c *CertificateCreate) SetIssuer(v string) *CertificateCreate {
	_c.mutation.SetIssuer(v)
	return _c
}

// SetYear sets the "year" field.
func (_c *CertificateCreate) SetYear(v string) *CertificateCreate {
	_c.mutation.SetYear(v)
	return _c
}

// SetVerificationLink sets the "verification_link" field.
func (_c *CertificateCreate) SetVerificationLink(v string) *CertificateCreate {
	_c.mutation.SetVerificationLink(v)
	return _c
}

// SetCredentialID sets the "credential_id" field.
func (_c *CertificateCreate) SetCredentialID(v string) *CertificateCreate {
	_c.mutation.SetCredentialID(v)
	return _c
}

// SetNillableCredentialID sets the "credential_id" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableCredentialID(v *string) *CertificateCreate {
	if v != nil {
		_c.SetCredentialID(*v)
	}
	return _c
}

// SetFeatured sets the "featured" field.
func (_c *CertificateCreate) SetFeatured(v bool) *CertificateCreate {
	_c.mutation.SetFeatured(v)
	return _c
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableFeatured(v *bool) *CertificateCreate {
	if v != nil {
		_c.SetFeatured(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *CertificateCreate) SetSortOrder(v int) *CertificateCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableSortOrder(v *int) *CertificateCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CertificateCreate) SetCreatedAt(v time.Time) *CertificateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableCreatedAt(v *time.Time) *CertificateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CertificateCreate) SetUpdatedAt(v time.Time) *CertificateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *CertificateCreate) SetID(v string) *CertificateCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CertificateMutation object of the builder.
func (_c *CertificateCreate) Mutation() *CertificateMutation {
	return _c.mutation
}

// Save creates the Certificate in the database.
func (_c *CertificateCreate) Save(ctx context.Context) (*Certificate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CertificateCreate) SaveX(ctx context.Context) *Certificate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CertificateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CertificateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CertificateCreate) defaults() {
	if _, ok := _c.mutation.Featured(); !ok {
		v := certificate.DefaultFeatured
		_c.mutation.SetFeatured(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := certificate.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := certificate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CertificateCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Certificate.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := certificate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Certificate.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Issuer(); !ok {
		return &ValidationError{Name: "issuer", err: errors.New(`ent: missing required field "Certificate.issuer"`)}
	}
	if v, ok := _c.mutation.Issuer(); ok {
		if err := certificate.IssuerValidator(v); err != nil {
			return &ValidationError{Name: "issuer", err: fmt.Errorf(`ent: validator failed for field "Certificate.issuer": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Year(); !ok {
		return &ValidationError{Name: "year", err: errors.New(`ent: missing required field "Certificate.year"`)}
	}
	if v, ok := _c.mutation.Year(); ok {
		if err := certificate.YearValidator(v); err != nil {
			return &ValidationError{Name: "year", err: fmt.Errorf(`ent: validator failed for field "Certificate.year": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VerificationLink(); !ok {
		return &ValidationError{Name: "verification_link", err: errors.New(`ent: missing required field "Certificate.verification_link"`)}
	}
	if v, ok := _c.mutation.VerificationLink(); ok {
		if err := certificate.VerificationLinkValidator(v); err != nil {
			return &ValidationError{Name: "verification_link", err: fmt.Errorf(`ent: validator failed for field "Certificate.verification_link": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Featured(); !ok {
		return &ValidationError{Name: "featured", err: errors.New(`ent: missing required field "Certificate.featured"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "Certificate.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Certificate.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Certificate.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := certificate.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Certificate.id": %w`, err)}
		}
	}
	return nil
}

func (_c *CertificateCreate) sqlSave(ctx context.Context) (*Certificate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Certificate.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CertificateCreate) createSpec() (*Certificate, *sqlgraph.CreateSpec) {
	var (
		_node = &Certificate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(certificate.Table, sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(certificate.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Issuer(); ok {
		_spec.SetField(certificate.FieldIssuer, field.TypeString, value)
		_node.Issuer = value
	}
	if value, ok := _c.mutation.Year(); ok {
		_spec.SetField(certificate.FieldYear, field.TypeString, value)
		_node.Year = value
	}
	if value, ok := _c.mutation.VerificationLink(); ok {
		_spec.SetField(certificate.FieldVerificationLink, field.TypeString, value)
		_node.VerificationLink = value
	}
	if value, ok := _c.mutation.CredentialID(); ok {
		_spec.SetField(certificate.FieldCredentialID, field.TypeString, value)
		_node.CredentialID = &value
	}
	if value, ok := _c.mutation.Featured(); ok {
		_spec.SetField(certificate.FieldFeatured, field.TypeBool, value)
		_node.Featured = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(certificate.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(certificate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(certificate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// CertificateCreateBulk is the builder for creating many Certificate entities in bulk.
type CertificateCreateBulk struct {
	config
	err      error
	builders []*CertificateCreate
}

// Save creates the Certificate entities in the database.
func (_c *CertificateCreateBulk) Save(ctx context.Context) ([]*Certificate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Certificate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CertificateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CertificateCreateBulk) SaveX(ctx context.Context) []*Certificate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CertificateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CertificateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
