// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/infrastructure/persistence/ent/cvdownloadlog"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CVDownloadLog is the model entity for the CVDownloadLog schema.
type CVDownloadLog struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// IPHash holds the value of the "ip_hash" field.
	IPHash string `json:"ip_hash,omitempty"`
	// UserAgent holds the value of the "user_agent" field.
	UserAgent string `json:"user_agent,omitempty"`
	// Referrer holds the value of the "referrer" field.
	Referrer string `json:"referrer,omitempty"`
	// DownloadedAt holds the value of the "downloaded_at" field.
	DownloadedAt time.Time `json:"downloaded_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CVDownloadLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cvdownloadlog.FieldID, cvdownloadlog.FieldIPHash, cvdownloadlog.FieldUserAgent, cvdownloadlog.FieldReferrer:
			values[i] = new(sql.NullString)
		case cvdownloadlog.FieldDownloadedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CVDownloadLog fields.
func (_m *CVDownloadLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cvdownloadlog.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case cvdownloadlog.FieldIPHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_hash", values[i])
			} else if value.Valid {
				_m.IPHash = value.String
			}
		case cvdownloadlog.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case cvdownloadlog.FieldReferrer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field referrer", values[i])
			} else if value.Valid {
				_m.Referrer = value.String
			}
		case cvdownloadlog.FieldDownloadedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field downloaded_at", values[i])
			} else if value.Valid {
				_m.DownloadedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CVDownloadLog.
// This includes values selected through modifiers, order, etc.
func (_m *CVDownloadLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CVDownloadLog.
// Note that you need to call CVDownloadLog.Unwrap() before calling this method if this CVDownloadLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CVDownloadLog) Update() *CVDownloadLogUpdateOne {
	return NewCVDownloadLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CVDownloadLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CVDownloadLog) Unwrap() *CVDownloadLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CVDownloadLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CVDownloadLog) String() string {
	var builder strings.Builder
	builder.WriteString("CVDownloadLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ip_hash=")
	builder.WriteString(_m.IPHash)
	builder.WriteString(", ")
	builder.WriteString("user_agent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("referrer=")
	builder.WriteString(_m.Referrer)
	builder.WriteString(", ")
	builder.WriteString("downloaded_at=")
	builder.WriteString(_m.DownloadedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CVDownloadLogs is a parsable slice of CVDownloadLog.
type CVDownloadLogs []*CVDownloadLog
