// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/infrastructure/persistence/ent/education"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EducationCreate is the builder for creating a Education entity.
type EducationCreate struct {
	config
	mutation *EducationMutation
	hooks    []Hook
}

// SetDegree sets the "degree" field.
func (_c *EducationCreate) SetDegree(v string) *EducationCreate {
	_c.mutation.SetDegree(v)
	return _c
}

// SetSchool sets the "school" field.
func (_c *EducationCreate) SetSchool(v string) *EducationCreate {
	_c.mutation.SetSchool(v)
	return _c
}

// SetPeriod sets the "period" field.
func (_c *EducationCreate) SetPeriod(v string) *EducationCreate {
	_c.mutation.SetPeriod(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *EducationCreate) SetDescription(v string) *EducationCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetHighlights sets the "highlights" field.
func (_c *EducationCreate) SetHighlights(v []string) *EducationCreate {
	_c.mutation.SetHighlights(v)
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *EducationCreate) SetSortOrder(v int) *EducationCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *EducationCreate) SetNillableSortOrder(v *int) *EducationCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EducationCreate) SetCreatedAt(v time.Time) *EducationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EducationCreate) SetNillableCreatedAt(v *time.Time) *EducationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EducationCreate) SetUpdatedAt(v time.Time) *EducationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *EducationCreate) SetID(v string) *EducationCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the EducationMutation object of the builder.
func (_c *EducationCreate) Mutation() *EducationMutation {
	return _c.mutation
}

// Save creates the Education in the database.
func (_c *EducationCreate) Save(ctx context.Context) (*Education, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EducationCreate) SaveX(ctx context.Context) *Education {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EducationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EducationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EducationCreate) defaults() {
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := education.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := education.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EducationCreate) check() error {
	if _, ok := _c.mutation.Degree(); !ok {
		return &ValidationError{Name: "degree", err: errors.New(`ent: missing required field "Education.degree"`)}
	}
	if v, ok := _c.mutation.Degree(); ok {
		if err := education.DegreeValidator(v); err != nil {
			return &ValidationError{Name: "degree", err: fmt.Errorf(`ent: validator failed for field "Education.degree": %w`, err)}
		}
	}
	if _, ok := _c.mutation.School(); !ok {
		return &ValidationError{Name: "school", err: errors.New(`ent: missing required field "Education.school"`)}
	}
	if v, ok := _c.mutation.School(); ok {
		if err := education.SchoolValidator(v); err != nil {
			return &ValidationError{Name: "school", err: fmt.Errorf(`ent: validator failed for field "Education.school": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Period(); !ok {
		return &ValidationError{Name: "period", err: errors.New(`ent: missing required field "Education.period"`)}
	}
	if v, ok := _c.mutation.Period(); ok {
		if err := education.PeriodValidator(v); err != nil {
			return &ValidationError{Name: "period", err: fmt.Errorf(`ent: validator failed for field "Education.period": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Education.description"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := education.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Education.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "Education.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Education.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Education.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := education.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Education.id": %w`, err)}
		}
	}
	return nil
}

func (_c *EducationCreate) sqlSave(ctx context.Context) (*Education, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Education.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EducationCreate) createSpec() (*Education, *sqlgraph.CreateSpec) {
	var (
		_node = &Education{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(education.Table, sqlgraph.NewFieldSpec(education.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Degree(); ok {
		_spec.SetField(education.FieldDegree, field.TypeString, value)
		_node.Degree = value
	}
	if value, ok := _c.mutation.School(); ok {
		_spec.SetField(education.FieldSchool, field.TypeString, value)
		_node.School = value
	}
	if value, ok := _c.mutation.Period(); ok {
		_spec.SetField(education.FieldPeriod, field.TypeString, value)
		_node.Period = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(education.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Highlights(); ok {
		_spec.SetField(education.FieldHighlights, field.TypeJSON, value)
		_node.Highlights = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(education.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(education.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(education.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// EducationCreateBulk is the builder for creating many Education entities in bulk.
type EducationCreateBulk struct {
	config
	err      error
	builders []*EducationCreate
}

// Save creates the Education entities in the database.
func (_c *EducationCreateBulk) Save(ctx context.Context) ([]*Education, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Education, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EducationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EducationCreateBulk) SaveX(ctx context.Context) []*Education {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EducationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EducationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
