// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/infrastructure/persistence/ent/profilecontent"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfileContentCreate is the builder for creating a ProfileContent entity.
type ProfileContentCreate struct {
	config
	mutation *ProfileContentMutation
	hooks    []Hook
}

// SetStorageKey sets the "storage_key" field.
func (_c *ProfileContentCreate) SetStorageKey(v string) *ProfileContentCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_c *ProfileContentCreate) SetNillableStorageKey(v *string) *ProfileContentCreate {
	if v != nil {
		_c.SetStorageKey(*v)
	}
	return _c
}

// SetFullName sets the "full_name" field.
func (_c *ProfileContentCreate) SetFullName(v string) *ProfileContentCreate {
	_c.mutation.SetFullName(v)
	return _c
}

// SetHeadline sets the "headline" field.
func (_c *ProfileContentCreate) SetHeadline(v string) *ProfileContentCreate {
	_c.mutation.SetHeadline(v)
	return _c
}

// SetShortIntro sets the "short_intro" field.
func (_c *ProfileContentCreate) SetShortIntro(v string) *ProfileContentCreate {
	_c.mutation.SetShortIntro(v)
	return _c
}

// SetAbout sets the "about" field.
func (_c *ProfileContentCreate) SetAbout(v string) *ProfileContentCreate {
	_c.mutation.SetAbout(v)
	return _c
}

// SetLocation sets the "location" field.
func (_c *ProfileContentCreate) SetLocation(v string) *ProfileContentCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *ProfileContentCreate) SetEmail(v string) *ProfileContentCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetPhone sets the "phone" field.
func (_c *ProfileContentCreate) SetPhone(v string) *ProfileContentCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetAvailability sets the "availability" field.
func (_c *ProfileContentCreate) SetAvailability(v string) *ProfileContentCreate {
	_c.mutation.SetAvailability(v)
	return _c
}

// SetPrimaryCta sets the "primary_cta" field.
func (_c *ProfileContentCreate) SetPrimaryCta(v string) *ProfileContentCreate {
	_c.mutation.SetPrimaryCta(v)
	return _c
}

// SetSocialLinks sets the "social_links" field.
func (_c *ProfileContentCreate) SetSocialLinks(v map[string]interface{}) *ProfileContentCreate {
	_c.mutation.SetSocialLinks(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProfileContentCreate) SetCreatedAt(v time.Time) *ProfileContentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProfileContentCreate) SetNillableCreatedAt(v *time.Time) *ProfileContentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProfileContentCreate) SetUpdatedAt(v time.Time) *ProfileContentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetProfilePhotoURL sets the "profile_photo_url" field.
func (_c *ProfileContentCreate) SetProfilePhotoURL(v string) *ProfileContentCreate {
	_c.mutation.SetProfilePhotoURL(v)
	return _c
}

// SetNillableProfilePhotoURL sets the "profile_photo_url" field if the given value is not nil.
func (_c *ProfileContentCreate) SetNillableProfilePhotoURL(v *string) *ProfileContentCreate {
	if v != nil {
		_c.SetProfilePhotoURL(*v)
	}
	return _c
}

// SetFocus sets the "focus" field.
func (_c *ProfileContentCreate) SetFocus(v []string) *ProfileContentCreate {
	_c.mutation.SetFocus(v)
	return _c
}

// SetStats sets the "stats" field.
func (_c *ProfileContentCreate) SetStats(v []interface{}) *ProfileContentCreate {
	_c.mutation.SetStats(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ProfileContentCreate) SetID(v string) *ProfileContentCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ProfileContentMutation object of the builder.
func (_c *ProfileContentCreate) Mutation() *ProfileContentMutation {
	return _c.mutation
}

// Save creates the ProfileContent in the database.
func (_c *ProfileContentCreate) Save(ctx context.Context) (*ProfileContent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProfileContentCreate) SaveX(ctx context.Context) *ProfileContent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProfileContentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProfileContentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProfileContentCreate) defaults() {
	if _, ok := _c.mutation.StorageKey(); !ok {
		v := profilecontent.DefaultStorageKey
		_c.mutation.SetStorageKey(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := profilecontent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Focus(); !ok {
		v := profilecontent.DefaultFocus
		_c.mutation.SetFocus(v)
	}
	if _, ok := _c.mutation.Stats(); !ok {
		v := profilecontent.DefaultStats
		_c.mutation.SetStats(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProfileContentCreate) check() error {
	if _, ok := _c.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storage_key", err: errors.New(`ent: missing required field "ProfileContent.storage_key"`)}
	}
	if v, ok := _c.mutation.StorageKey(); ok {
		if err := profilecontent.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "ProfileContent.storage_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FullName(); !ok {
		return &ValidationError{Name: "full_name", err: errors.New(`ent: missing required field "ProfileContent.full_name"`)}
	}
	if v, ok := _c.mutation.FullName(); ok {
		if err := profilecontent.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "ProfileContent.full_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Headline(); !ok {
		return &ValidationError{Name: "headline", err: errors.New(`ent: missing required field "ProfileContent.headline"`)}
	}
	if v, ok := _c.mutation.Headline(); ok {
		if err := profilecontent.HeadlineValidator(v); err != nil {
			return &ValidationError{Name: "headline", err: fmt.Errorf(`ent: validator failed for field "ProfileContent.headline": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ShortIntro(); !ok {
		return &ValidationError{Name: "short_intro", err: errors.New(`ent: missing required field "ProfileContent.short_intro"`)}
	}
	if v, ok := _c.mutation.ShortIntro(); ok {
		if err := profilecontent.ShortIntroValidator(v); err != nil {
			return &ValidationError{Name: "short_intro", err: fmt.Errorf(`ent: validator failed for field "ProfileContent.short_intro": %w`, err)}
		}
	}
	if _, ok := _c.mutation.About(); !ok {
		return &ValidationError{Name: "about", err: errors.New(`ent: missing required field "ProfileContent.about"`)}
	}
	if v, ok := _c.mutation.About(); ok {
		if err := profilecontent.AboutValidator(v); err != nil {
			return &ValidationError{Name: "about", err: fmt.Errorf(`ent: validator failed for field "ProfileContent.about": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Location(); !ok {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required field "ProfileContent.location"`)}
	}
	if v, ok := _c.mutation.Location(); ok {
		if err := profilecontent.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "ProfileContent.location": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "ProfileContent.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := profilecontent.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "ProfileContent.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New(`ent: missing required field "ProfileContent.phone"`)}
	}
	if v, ok := _c.mutation.Phone(); ok {
		if err := profilecontent.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "ProfileContent.phone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Availability(); !ok {
		return &ValidationError{Name: "availability", err: errors.New(`ent: missing required field "ProfileContent.availability"`)}
	}
	if v, ok := _c.mutation.Availability(); ok {
		if err := profilecontent.AvailabilityValidator(v); err != nil {
			return &ValidationError{Name: "availability", err: fmt.Errorf(`ent: validator failed for field "ProfileContent.availability": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PrimaryCta(); !ok {
		return &ValidationError{Name: "primary_cta", err: errors.New(`ent: missing required field "ProfileContent.primary_cta"`)}
	}
	if v, ok := _c.mutation.PrimaryCta(); ok {
		if err := profilecontent.PrimaryCtaValidator(v); err != nil {
			return &ValidationError{Name: "primary_cta", err: fmt.Errorf(`ent: validator failed for field "ProfileContent.primary_cta": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SocialLinks(); !ok {
		return &ValidationError{Name: "social_links", err: errors.New(`ent: missing required field "ProfileContent.social_links"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProfileContent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProfileContent.updated_at"`)}
	}
	if _, ok := _c.mutation.Focus(); !ok {
		return &ValidationError{Name: "focus", err: errors.New(`ent: missing required field "ProfileContent.focus"`)}
	}
	if _, ok := _c.mutation.Stats(); !ok {
		return &ValidationError{Name: "stats", err: errors.New(`ent: missing required field "ProfileContent.stats"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := profilecontent.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ProfileContent.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ProfileContentCreate) sqlSave(ctx context.Context) (*ProfileContent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ProfileContent.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProfileContentCreate) createSpec() (*ProfileContent, *sqlgraph.CreateSpec) {
	var (
		_node = &ProfileContent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(profilecontent.Table, sqlgraph.NewFieldSpec(profilecontent.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(profilecontent.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if value, ok := _c.mutation.FullName(); ok {
		_spec.SetField(profilecontent.FieldFullName, field.TypeString, value)
		_node.FullName = value
	}
	if value, ok := _c.mutation.Headline(); ok {
		_spec.SetField(profilecontent.FieldHeadline, field.TypeString, value)
		_node.Headline = value
	}
	if value, ok := _c.mutation.ShortIntro(); ok {
		_spec.SetField(profilecontent.FieldShortIntro, field.TypeString, value)
		_node.ShortIntro = value
	}
	if value, ok := _c.mutation.About(); ok {
		_spec.SetField(profilecontent.FieldAbout, field.TypeString, value)
		_node.About = value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(profilecontent.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(profilecontent.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(profilecontent.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.Availability(); ok {
		_spec.SetField(profilecontent.FieldAvailability, field.TypeString, value)
		_node.Availability = value
	}
	if value, ok := _c.mutation.PrimaryCta(); ok {
		_spec.SetField(profilecontent.FieldPrimaryCta, field.TypeString, value)
		_node.PrimaryCta = value
	}
	if value, ok := _c.mutation.SocialLinks(); ok {
		_spec.SetField(profilecontent.FieldSocialLinks, field.TypeJSON, value)
		_node.SocialLinks = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(profilecontent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(profilecontent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ProfilePhotoURL(); ok {
		_spec.SetField(profilecontent.FieldProfilePhotoURL, field.TypeString, value)
		_node.ProfilePhotoURL = &value
	}
	if value, ok := _c.mutation.Focus(); ok {
		_spec.SetField(profilecontent.FieldFocus, field.TypeJSON, value)
		_node.Focus = value
	}
	if value, ok := _c.mutation.Stats(); ok {
		_spec.SetField(profilecontent.FieldStats, field.TypeJSON, value)
		_node.Stats = value
	}
	return _node, _spec
}

// ProfileContentCreateBulk is the builder for creating many ProfileContent entities in bulk.
type ProfileContentCreateBulk struct {
	config
	err      error
	builders []*ProfileContentCreate
}

// Save creates the ProfileContent entities in the database.
func (_c *ProfileContentCreateBulk) Save(ctx context.Context) ([]*ProfileContent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProfileContent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProfileContentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProfileContentCreateBulk) SaveX(ctx context.Context) []*ProfileContent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProfileContentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProfileContentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
