// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/infrastructure/persistence/ent/testimonial"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Testimonial is the model entity for the Testimonial schema.
type Testimonial struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// Company holds the value of the "company" field.
	Company *string `json:"company,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// Rating holds the value of the "rating" field.
	Rating int `json:"rating,omitempty"`
	// Relation holds the value of the "relation" field.
	Relation testimonial.Relation `json:"relation,omitempty"`
	// Status holds the value of the "status" field.
	Status testimonial.Status `json:"status,omitempty"`
	// Featured holds the value of the "featured" field.
	Featured bool `json:"featured,omitempty"`
	// ReviewedAt holds the value of the "reviewed_at" field.
	ReviewedAt *time.Time `json:"reviewed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Testimonial) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case testimonial.FieldFeatured:
			values[i] = new(sql.NullBool)
		case testimonial.FieldRating:
			values[i] = new(sql.NullInt64)
		case testimonial.FieldID, testimonial.FieldName, testimonial.FieldRole, testimonial.FieldCompany, testimonial.FieldMessage, testimonial.FieldRelation, testimonial.FieldStatus:
			values[i] = new(sql.NullString)
		case testimonial.FieldReviewedAt, testimonial.FieldCreatedAt, testimonial.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Testimonial fields.
func (_m *Testimonial) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case testimonial.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case testimonial.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case testimonial.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case testimonial.FieldCompany:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field company", values[i])
			} else if value.Valid {
				_m.Company = new(string)
				*_m.Company = value.String
			}
		case testimonial.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case testimonial.FieldRating:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rating", values[i])
			} else if value.Valid {
				_m.Rating = int(value.Int64)
			}
		case testimonial.FieldRelation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field relation", values[i])
			} else if value.Valid {
				_m.Relation = testimonial.Relation(value.String)
			}
		case testimonial.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = testimonial.Status(value.String)
			}
		case testimonial.FieldFeatured:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field featured", values[i])
			} else if value.Valid {
				_m.Featured = value.Bool
			}
		case testimonial.FieldReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_at", values[i])
			} else if value.Valid {
				_m.ReviewedAt = new(time.Time)
				*_m.ReviewedAt = value.Time
			}
		case testimonial.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case testimonial.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Testimonial.
// This includes values selected through modifiers, order, etc.
func (_m *Testimonial) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Testimonial.
// Note that you need to call Testimonial.Unwrap() before calling this method if this Testimonial
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Testimonial) Update() *TestimonialUpdateOne {
	return NewTestimonialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Testimonial entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Testimonial) Unwrap() *Testimonial {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Testimonial is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Testimonial) String() string {
	var builder strings.Builder
	builder.WriteString("Testimonial(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	if v := _m.Company; v != nil {
		builder.WriteString("company=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("rating=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rating))
	builder.WriteString(", ")
	builder.WriteString("relation=")
	builder.WriteString(fmt.Sprintf("%v", _m.Relation))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("featured=")
	builder.WriteString(fmt.Sprintf("%v", _m.Featured))
	builder.WriteString(", ")
	if v := _m.ReviewedAt; v != nil {
		builder.WriteString("reviewed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Testimonials is a parsable slice of Testimonial.
type Testimonials []*Testimonial
