// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/infrastructure/persistence/ent/predicate"
	"api/internal/infrastructure/persistence/ent/testimonial"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TestimonialUpdate is the builder for updating Testimonial entities.
type TestimonialUpdate struct {
	config
	hooks    []Hook
	mutation *TestimonialMutation
}

// Where appends a list predicates to the TestimonialUpdate builder.
func (_u *TestimonialUpdate) Where(ps ...predicate.Testimonial) *TestimonialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TestimonialUpdate) SetName(v string) *TestimonialUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TestimonialUpdate) SetNillableName(v *string) *TestimonialUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *TestimonialUpdate) SetRole(v string) *TestimonialUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *TestimonialUpdate) SetNillableRole(v *string) *TestimonialUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetCompany sets the "company" field.
func (_u *TestimonialUpdate) SetCompany(v string) *TestimonialUpdate {
	_u.mutation.SetCompany(v)
	return _u
}

// SetNillableCompany sets the "company" field if the given value is not nil.
func (_u *TestimonialUpdate) SetNillableCompany(v *string) *TestimonialUpdate {
	if v != nil {
		_u.SetCompany(*v)
	}
	return _u
}

// ClearCompany clears the value of the "company" field.
func (_u *TestimonialUpdate) ClearCompany() *TestimonialUpdate {
	_u.mutation.ClearCompany()
	return _u
}

// SetMessage sets the "message" field.
func (_u *TestimonialUpdate) SetMessage(v string) *TestimonialUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *TestimonialUpdate) SetNillableMessage(v *string) *TestimonialUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *TestimonialUpdate) SetRating(v int) *TestimonialUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *TestimonialUpdate) SetNillableRating(v *int) *TestimonialUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *TestimonialUpdate) AddRating(v int) *TestimonialUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// SetRelation sets the "relation" field.
func (_u *TestimonialUpdate) SetRelation(v testimonial.Relation) *TestimonialUpdate {
	_u.mutation.SetRelation(v)
	return _u
}

// SetNillableRelation sets the "relation" field if the given value is not nil.
func (_u *TestimonialUpdate) SetNillableRelation(v *testimonial.Relation) *TestimonialUpdate {
	if v != nil {
		_u.SetRelation(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TestimonialUpdate) SetStatus(v testimonial.Status) *TestimonialUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TestimonialUpdate) SetNillableStatus(v *testimonial.Status) *TestimonialUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFeatured sets the "featured" field.
func (_u *TestimonialUpdate) SetFeatured(v bool) *TestimonialUpdate {
	_u.mutation.SetFeatured(v)
	return _u
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_u *TestimonialUpdate) SetNillableFeatured(v *bool) *TestimonialUpdate {
	if v != nil {
		_u.SetFeatured(*v)
	}
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *TestimonialUpdate) SetReviewedAt(v time.Time) *TestimonialUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *TestimonialUpdate) SetNillableReviewedAt(v *time.Time) *TestimonialUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *TestimonialUpdate) ClearReviewedAt() *TestimonialUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TestimonialUpdate) SetCreatedAt(v time.Time) *TestimonialUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TestimonialUpdate) SetNillableCreatedAt(v *time.Time) *TestimonialUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TestimonialUpdate) SetUpdatedAt(v time.Time) *TestimonialUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TestimonialMutation object of the builder.
func (_u *TestimonialUpdate) Mutation() *TestimonialMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TestimonialUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TestimonialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TestimonialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TestimonialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TestimonialUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := testimonial.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TestimonialUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := testimonial.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Testimonial.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := testimonial.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Testimonial.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Message(); ok {
		if err := testimonial.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Testimonial.message": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Relation(); ok {
		if err := testimonial.RelationValidator(v); err != nil {
			return &ValidationError{Name: "relation", err: fmt.Errorf(`ent: validator failed for field "Testimonial.relation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := testimonial.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Testimonial.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TestimonialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(testimonial.Table, testimonial.Columns, sqlgraph.NewFieldSpec(testimonial.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(testimonial.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(testimonial.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Company(); ok {
		_spec.SetField(testimonial.FieldCompany, field.TypeString, value)
	}
	if _u.mutation.CompanyCleared() {
		_spec.ClearField(testimonial.FieldCompany, field.TypeString)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(testimonial.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(testimonial.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(testimonial.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Relation(); ok {
		_spec.SetField(testimonial.FieldRelation, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(testimonial.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Featured(); ok {
		_spec.SetField(testimonial.FieldFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(testimonial.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(testimonial.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(testimonial.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(testimonial.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{testimonial.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TestimonialUpdateOne is the builder for updating a single Testimonial entity.
type TestimonialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TestimonialMutation
}

// SetName sets the "name" field.
func (_u *TestimonialUpdateOne) SetName(v string) *TestimonialUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TestimonialUpdateOne) SetNillableName(v *string) *TestimonialUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *TestimonialUpdateOne) SetRole(v string) *TestimonialUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *TestimonialUpdateOne) SetNillableRole(v *string) *TestimonialUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetCompany sets the "company" field.
func (_u *TestimonialUpdateOne) SetCompany(v string) *TestimonialUpdateOne {
	_u.mutation.SetCompany(v)
	return _u
}

// SetNillableCompany sets the "company" field if the given value is not nil.
func (_u *TestimonialUpdateOne) SetNillableCompany(v *string) *TestimonialUpdateOne {
	if v != nil {
		_u.SetCompany(*v)
	}
	return _u
}

// ClearCompany clears the value of the "company" field.
func (_u *TestimonialUpdateOne) ClearCompany() *TestimonialUpdateOne {
	_u.mutation.ClearCompany()
	return _u
}

// SetMessage sets the "message" field.
func (_u *TestimonialUpdateOne) SetMessage(v string) *TestimonialUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *TestimonialUpdateOne) SetNillableMessage(v *string) *TestimonialUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *TestimonialUpdateOne) SetRating(v int) *TestimonialUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *TestimonialUpdateOne) SetNillableRating(v *int) *TestimonialUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *TestimonialUpdateOne) AddRating(v int) *TestimonialUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// SetRelation sets the "relation" field.
func (_u *TestimonialUpdateOne) SetRelation(v testimonial.Relation) *TestimonialUpdateOne {
	_u.mutation.SetRelation(v)
	return _u
}

// SetNillableRelation sets the "relation" field if the given value is not nil.
func (_u *TestimonialUpdateOne) SetNillableRelation(v *testimonial.Relation) *TestimonialUpdateOne {
	if v != nil {
		_u.SetRelation(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TestimonialUpdateOne) SetStatus(v testimonial.Status) *TestimonialUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TestimonialUpdateOne) SetNillableStatus(v *testimonial.Status) *TestimonialUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFeatured sets the "featured" field.
func (_u *TestimonialUpdateOne) SetFeatured(v bool) *TestimonialUpdateOne {
	_u.mutation.SetFeatured(v)
	return _u
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_u *TestimonialUpdateOne) SetNillableFeatured(v *bool) *TestimonialUpdateOne {
	if v != nil {
		_u.SetFeatured(*v)
	}
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *TestimonialUpdateOne) SetReviewedAt(v time.Time) *TestimonialUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *TestimonialUpdateOne) SetNillableReviewedAt(v *time.Time) *TestimonialUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *TestimonialUpdateOne) ClearReviewedAt() *TestimonialUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TestimonialUpdateOne) SetCreatedAt(v time.Time) *TestimonialUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TestimonialUpdateOne) SetNillableCreatedAt(v *time.Time) *TestimonialUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TestimonialUpdateOne) SetUpdatedAt(v time.Time) *TestimonialUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TestimonialMutation object of the builder.
func (_u *TestimonialUpdateOne) Mutation() *TestimonialMutation {
	return _u.mutation
}

// Where appends a list predicates to the TestimonialUpdate builder.
func (_u *TestimonialUpdateOne) Where(ps ...predicate.Testimonial) *TestimonialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TestimonialUpdateOne) Select(field string, fields ...string) *TestimonialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Testimonial entity.
func (_u *TestimonialUpdateOne) Save(ctx context.Context) (*Testimonial, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TestimonialUpdateOne) SaveX(ctx context.Context) *Testimonial {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TestimonialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TestimonialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TestimonialUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := testimonial.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TestimonialUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := testimonial.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Testimonial.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := testimonial.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Testimonial.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Message(); ok {
		if err := testimonial.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Testimonial.message": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Relation(); ok {
		if err := testimonial.RelationValidator(v); err != nil {
			return &ValidationError{Name: "relation", err: fmt.Errorf(`ent: validator failed for field "Testimonial.relation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := testimonial.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Testimonial.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TestimonialUpdateOne) sqlSave(ctx context.Context) (_node *Testimonial, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(testimonial.Table, testimonial.Columns, sqlgraph.NewFieldSpec(testimonial.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Testimonial.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, testimonial.FieldID)
		for _, f := range fields {
			if !testimonial.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != testimonial.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(testimonial.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(testimonial.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Company(); ok {
		_spec.SetField(testimonial.FieldCompany, field.TypeString, value)
	}
	if _u.mutation.CompanyCleared() {
		_spec.ClearField(testimonial.FieldCompany, field.TypeString)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(testimonial.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(testimonial.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(testimonial.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Relation(); ok {
		_spec.SetField(testimonial.FieldRelation, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(testimonial.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Featured(); ok {
		_spec.SetField(testimonial.FieldFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(testimonial.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(testimonial.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(testimonial.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(testimonial.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Testimonial{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{testimonial.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
