// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/infrastructure/persistence/ent/predicate"
	"api/internal/infrastructure/persistence/ent/visitorlog"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VisitorLogUpdate is the builder for updating VisitorLog entities.
type VisitorLogUpdate struct {
	config
	hooks    []Hook
	mutation *VisitorLogMutation
}

// Where appends a list predicates to the VisitorLogUpdate builder.
func (_u *VisitorLogUpdate) Where(ps ...predicate.VisitorLog) *VisitorLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetVisitorID sets the "visitor_id" field.
func (_u *VisitorLogUpdate) SetVisitorID(v string) *VisitorLogUpdate {
	_u.mutation.SetVisitorID(v)
	return _u
}

// SetNillableVisitorID sets the "visitor_id" field if the given value is not nil.
func (_u *VisitorLogUpdate) SetNillableVisitorID(v *string) *VisitorLogUpdate {
	if v != nil {
		_u.SetVisitorID(*v)
	}
	return _u
}

// SetIPHash sets the "ip_hash" field.
func (_u *VisitorLogUpdate) SetIPHash(v string) *VisitorLogUpdate {
	_u.mutation.SetIPHash(v)
	return _u
}

// SetNillableIPHash sets the "ip_hash" field if the given value is not nil.
func (_u *VisitorLogUpdate) SetNillableIPHash(v *string) *VisitorLogUpdate {
	if v != nil {
		_u.SetIPHash(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *VisitorLogUpdate) SetPath(v string) *VisitorLogUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *VisitorLogUpdate) SetNillablePath(v *string) *VisitorLogUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetReferrer sets the "referrer" field.
func (_u *VisitorLogUpdate) SetReferrer(v string) *VisitorLogUpdate {
	_u.mutation.SetReferrer(v)
	return _u
}

// SetNillableReferrer sets the "referrer" field if the given value is not nil.
func (_u *VisitorLogUpdate) SetNillableReferrer(v *string) *VisitorLogUpdate {
	if v != nil {
		_u.SetReferrer(*v)
	}
	return _u
}

// SetReferrerSource sets the "referrer_source" field.
func (_u *VisitorLogUpdate) SetReferrerSource(v string) *VisitorLogUpdate {
	_u.mutation.SetReferrerSource(v)
	return _u
}

// SetNillableReferrerSource sets the "referrer_source" field if the given value is not nil.
func (_u *VisitorLogUpdate) SetNillableReferrerSource(v *string) *VisitorLogUpdate {
	if v != nil {
		_u.SetReferrerSource(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *VisitorLogUpdate) SetUserAgent(v string) *VisitorLogUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *VisitorLogUpdate) SetNillableUserAgent(v *string) *VisitorLogUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetIsUniqueDailyVisitor sets the "is_unique_daily_visitor" field.
func (_u *VisitorLogUpdate) SetIsUniqueDailyVisitor(v bool) *VisitorLogUpdate {
	_u.mutation.SetIsUniqueDailyVisitor(v)
	return _u
}

// SetNillableIsUniqueDailyVisitor sets the "is_unique_daily_visitor" field if the given value is not nil.
func (_u *VisitorLogUpdate) SetNillableIsUniqueDailyVisitor(v *bool) *VisitorLogUpdate {
	if v != nil {
		_u.SetIsUniqueDailyVisitor(*v)
	}
	return _u
}

// SetVisitedAt sets the "visited_at" field.
func (_u *VisitorLogUpdate) SetVisitedAt(v time.Time) *VisitorLogUpdate {
	_u.mutation.SetVisitedAt(v)
	return _u
}

// SetNillableVisitedAt sets the "visited_at" field if the given value is not nil.
func (_u *VisitorLogUpdate) SetNillableVisitedAt(v *time.Time) *VisitorLogUpdate {
	if v != nil {
		_u.SetVisitedAt(*v)
	}
	return _u
}

// Mutation returns the VisitorLogMutation object of the builder.
func (_u *VisitorLogUpdate) Mutation() *VisitorLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VisitorLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VisitorLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VisitorLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VisitorLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VisitorLogUpdate) check() error {
	if v, ok := _u.mutation.VisitorID(); ok {
		if err := visitorlog.VisitorIDValidator(v); err != nil {
			return &ValidationError{Name: "visitor_id", err: fmt.Errorf(`ent: validator failed for field "VisitorLog.visitor_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPHash(); ok {
		if err := visitorlog.IPHashValidator(v); err != nil {
			return &ValidationError{Name: "ip_hash", err: fmt.Errorf(`ent: validator failed for field "VisitorLog.ip_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := visitorlog.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "VisitorLog.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Referrer(); ok {
		if err := visitorlog.ReferrerValidator(v); err != nil {
			return &ValidationError{Name: "referrer", err: fmt.Errorf(`ent: validator failed for field "VisitorLog.referrer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReferrerSource(); ok {
		if err := visitorlog.ReferrerSourceValidator(v); err != nil {
			return &ValidationError{Name: "referrer_source", err: fmt.Errorf(`ent: validator failed for field "VisitorLog.referrer_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := visitorlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "VisitorLog.user_agent": %w`, err)}
		}
	}
	return nil
}

func (_u *VisitorLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(visitorlog.Table, visitorlog.Columns, sqlgraph.NewFieldSpec(visitorlog.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.VisitorID(); ok {
		_spec.SetField(visitorlog.FieldVisitorID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IPHash(); ok {
		_spec.SetField(visitorlog.FieldIPHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(visitorlog.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Referrer(); ok {
		_spec.SetField(visitorlog.FieldReferrer, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReferrerSource(); ok {
		_spec.SetField(visitorlog.FieldReferrerSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(visitorlog.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsUniqueDailyVisitor(); ok {
		_spec.SetField(visitorlog.FieldIsUniqueDailyVisitor, field.TypeBool, value)
	}
	if value, ok := _u.mutation.VisitedAt(); ok {
		_spec.SetField(visitorlog.FieldVisitedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{visitorlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VisitorLogUpdateOne is the builder for updating a single VisitorLog entity.
type VisitorLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VisitorLogMutation
}

// SetVisitorID sets the "visitor_id" field.
func (_u *VisitorLogUpdateOne) SetVisitorID(v string) *VisitorLogUpdateOne {
	_u.mutation.SetVisitorID(v)
	return _u
}

// SetNillableVisitorID sets the "visitor_id" field if the given value is not nil.
func (_u *VisitorLogUpdateOne) SetNillableVisitorID(v *string) *VisitorLogUpdateOne {
	if v != nil {
		_u.SetVisitorID(*v)
	}
	return _u
}

// SetIPHash sets the "ip_hash" field.
func (_u *VisitorLogUpdateOne) SetIPHash(v string) *VisitorLogUpdateOne {
	_u.mutation.SetIPHash(v)
	return _u
}

// SetNillableIPHash sets the "ip_hash" field if the given value is not nil.
func (_u *VisitorLogUpdateOne) SetNillableIPHash(v *string) *VisitorLogUpdateOne {
	if v != nil {
		_u.SetIPHash(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *VisitorLogUpdateOne) SetPath(v string) *VisitorLogUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *VisitorLogUpdateOne) SetNillablePath(v *string) *VisitorLogUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetReferrer sets the "referrer" field.
func (_u *VisitorLogUpdateOne) SetReferrer(v string) *VisitorLogUpdateOne {
	_u.mutation.SetReferrer(v)
	return _u
}

// SetNillableReferrer sets the "referrer" field if the given value is not nil.
func (_u *VisitorLogUpdateOne) SetNillableReferrer(v *string) *VisitorLogUpdateOne {
	if v != nil {
		_u.SetReferrer(*v)
	}
	return _u
}

// SetReferrerSource sets the "referrer_source" field.
func (_u *VisitorLogUpdateOne) SetReferrerSource(v string) *VisitorLogUpdateOne {
	_u.mutation.SetReferrerSource(v)
	return _u
}

// SetNillableReferrerSource sets the "referrer_source" field if the given value is not nil.
func (_u *VisitorLogUpdateOne) SetNillableReferrerSource(v *string) *VisitorLogUpdateOne {
	if v != nil {
		_u.SetReferrerSource(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *VisitorLogUpdateOne) SetUserAgent(v string) *VisitorLogUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *VisitorLogUpdateOne) SetNillableUserAgent(v *string) *VisitorLogUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetIsUniqueDailyVisitor sets the "is_unique_daily_visitor" field.
func (_u *VisitorLogUpdateOne) SetIsUniqueDailyVisitor(v bool) *VisitorLogUpdateOne {
	_u.mutation.SetIsUniqueDailyVisitor(v)
	return _u
}

// SetNillableIsUniqueDailyVisitor sets the "is_unique_daily_visitor" field if the given value is not nil.
func (_u *VisitorLogUpdateOne) SetNillableIsUniqueDailyVisitor(v *bool) *VisitorLogUpdateOne {
	if v != nil {
		_u.SetIsUniqueDailyVisitor(*v)
	}
	return _u
}

// SetVisitedAt sets the "visited_at" field.
func (_u *VisitorLogUpdateOne) SetVisitedAt(v time.Time) *VisitorLogUpdateOne {
	_u.mutation.SetVisitedAt(v)
	return _u
}

// SetNillableVisitedAt sets the "visited_at" field if the given value is not nil.
func (_u *VisitorLogUpdateOne) SetNillableVisitedAt(v *time.Time) *VisitorLogUpdateOne {
	if v != nil {
		_u.SetVisitedAt(*v)
	}
	return _u
}

// Mutation returns the VisitorLogMutation object of the builder.
func (_u *VisitorLogUpdateOne) Mutation() *VisitorLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the VisitorLogUpdate builder.
func (_u *VisitorLogUpdateOne) Where(ps ...predicate.VisitorLog) *VisitorLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VisitorLogUpdateOne) Select(field string, fields ...string) *VisitorLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VisitorLog entity.
func (_u *VisitorLogUpdateOne) Save(ctx context.Context) (*VisitorLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VisitorLogUpdateOne) SaveX(ctx context.Context) *VisitorLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VisitorLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VisitorLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VisitorLogUpdateOne) check() error {
	if v, ok := _u.mutation.VisitorID(); ok {
		if err := visitorlog.VisitorIDValidator(v); err != nil {
			return &ValidationError{Name: "visitor_id", err: fmt.Errorf(`ent: validator failed for field "VisitorLog.visitor_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPHash(); ok {
		if err := visitorlog.IPHashValidator(v); err != nil {
			return &ValidationError{Name: "ip_hash", err: fmt.Errorf(`ent: validator failed for field "VisitorLog.ip_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := visitorlog.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "VisitorLog.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Referrer(); ok {
		if err := visitorlog.ReferrerValidator(v); err != nil {
			return &ValidationError{Name: "referrer", err: fmt.Errorf(`ent: validator failed for field "VisitorLog.referrer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReferrerSource(); ok {
		if err := visitorlog.ReferrerSourceValidator(v); err != nil {
			return &ValidationError{Name: "referrer_source", err: fmt.Errorf(`ent: validator failed for field "VisitorLog.referrer_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := visitorlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "VisitorLog.user_agent": %w`, err)}
		}
	}
	return nil
}

func (_u *VisitorLogUpdateOne) sqlSave(ctx context.Context) (_node *VisitorLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(visitorlog.Table, visitorlog.Columns, sqlgraph.NewFieldSpec(visitorlog.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VisitorLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, visitorlog.FieldID)
		for _, f := range fields {
			if !visitorlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != visitorlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.VisitorID(); ok {
		_spec.SetField(visitorlog.FieldVisitorID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IPHash(); ok {
		_spec.SetField(visitorlog.FieldIPHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(visitorlog.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Referrer(); ok {
		_spec.SetField(visitorlog.FieldReferrer, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReferrerSource(); ok {
		_spec.SetField(visitorlog.FieldReferrerSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(visitorlog.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsUniqueDailyVisitor(); ok {
		_spec.SetField(visitorlog.FieldIsUniqueDailyVisitor, field.TypeBool, value)
	}
	if value, ok := _u.mutation.VisitedAt(); ok {
		_spec.SetField(visitorlog.FieldVisitedAt, field.TypeTime, value)
	}
	_node = &VisitorLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{visitorlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
