// Code generated by ent, DO NOT EDIT.

package testimonial

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the testimonial type in the database.
	Label = "testimonial"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldCompany holds the string denoting the company field in the database.
	FieldCompany = "company"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldRating holds the string denoting the rating field in the database.
	FieldRating = "rating"
	// FieldRelation holds the string denoting the relation field in the database.
	FieldRelation = "relation"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFeatured holds the string denoting the featured field in the database.
	FieldFeatured = "featured"
	// FieldReviewedAt holds the string denoting the reviewed_at field in the database.
	FieldReviewedAt = "reviewedAt"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "createdAt"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updatedAt"
	// Table holds the table name of the testimonial in the database.
	Table = "testimonial"
)

// Columns holds all SQL columns for testimonial fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldRole,
	FieldCompany,
	FieldMessage,
	FieldRating,
	FieldRelation,
	FieldStatus,
	FieldFeatured,
	FieldReviewedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// RoleValidator is a validator for the "role" field. It is called by the builders before save.
	RoleValidator func(string) error
	// MessageValidator is a validator for the "message" field. It is called by the builders before save.
	MessageValidator func(string) error
	// DefaultFeatured holds the default value on creation for the "featured" field.
	DefaultFeatured bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Relation defines the type for the "relation" enum field.
type Relation string

// Relation values.
const (
	RelationCLIENT    Relation = "CLIENT"
	RelationCOLLEAGUE Relation = "COLLEAGUE"
	RelationMENTOR    Relation = "MENTOR"
	RelationOTHER     Relation = "OTHER"
)

func (r Relation) String() string {
	return string(r)
}

// RelationValidator is a validator for the "relation" field enum values. It is called by the builders before save.
func RelationValidator(r Relation) error {
	switch r {
	case RelationCLIENT, RelationCOLLEAGUE, RelationMENTOR, RelationOTHER:
		return nil
	default:
		return fmt.Errorf("testimonial: invalid enum value for relation field: %q", r)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING is the default value of the Status enum.
const DefaultStatus = StatusPENDING

// Status values.
const (
	StatusPENDING  Status = "PENDING"
	StatusAPPROVED Status = "APPROVED"
	StatusREJECTED Status = "REJECTED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPENDING, StatusAPPROVED, StatusREJECTED:
		return nil
	default:
		return fmt.Errorf("testimonial: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Testimonial queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByCompany orders the results by the company field.
func ByCompany(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompany, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}

// ByRating orders the results by the rating field.
func ByRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRating, opts...).ToFunc()
}

// ByRelation orders the results by the relation field.
func ByRelation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelation, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFeatured orders the results by the featured field.
func ByFeatured(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeatured, opts...).ToFunc()
}

// ByReviewedAt orders the results by the reviewed_at field.
func ByReviewedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
