// Code generated by ent, DO NOT EDIT.

package message

import (
	"api/internal/infrastructure/persistence/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldID, id))
}

// SenderName applies equality check predicate on the "sender_name" field. It's identical to SenderNameEQ.
func SenderName(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSenderName, v))
}

// SenderEmail applies equality check predicate on the "sender_email" field. It's identical to SenderEmailEQ.
func SenderEmail(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSenderEmail, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSubject, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldBody, v))
}

// ReadAt applies equality check predicate on the "read_at" field. It's identical to ReadAtEQ.
func ReadAt(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldReadAt, v))
}

// ArchivedAt applies equality check predicate on the "archived_at" field. It's identical to ArchivedAtEQ.
func ArchivedAt(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldArchivedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldUpdatedAt, v))
}

// SenderNameEQ applies the EQ predicate on the "sender_name" field.
func SenderNameEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSenderName, v))
}

// SenderNameNEQ applies the NEQ predicate on the "sender_name" field.
func SenderNameNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldSenderName, v))
}

// SenderNameIn applies the In predicate on the "sender_name" field.
func SenderNameIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldSenderName, vs...))
}

// SenderNameNotIn applies the NotIn predicate on the "sender_name" field.
func SenderNameNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldSenderName, vs...))
}

// SenderNameGT applies the GT predicate on the "sender_name" field.
func SenderNameGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldSenderName, v))
}

// SenderNameGTE applies the GTE predicate on the "sender_name" field.
func SenderNameGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldSenderName, v))
}

// SenderNameLT applies the LT predicate on the "sender_name" field.
func SenderNameLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldSenderName, v))
}

// SenderNameLTE applies the LTE predicate on the "sender_name" field.
func SenderNameLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldSenderName, v))
}

// SenderNameContains applies the Contains predicate on the "sender_name" field.
func SenderNameContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldSenderName, v))
}

// SenderNameHasPrefix applies the HasPrefix predicate on the "sender_name" field.
func SenderNameHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldSenderName, v))
}

// SenderNameHasSuffix applies the HasSuffix predicate on the "sender_name" field.
func SenderNameHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldSenderName, v))
}

// SenderNameEqualFold applies the EqualFold predicate on the "sender_name" field.
func SenderNameEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldSenderName, v))
}

// SenderNameContainsFold applies the ContainsFold predicate on the "sender_name" field.
func SenderNameContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldSenderName, v))
}

// SenderEmailEQ applies the EQ predicate on the "sender_email" field.
func SenderEmailEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSenderEmail, v))
}

// SenderEmailNEQ applies the NEQ predicate on the "sender_email" field.
func SenderEmailNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldSenderEmail, v))
}

// SenderEmailIn applies the In predicate on the "sender_email" field.
func SenderEmailIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldSenderEmail, vs...))
}

// SenderEmailNotIn applies the NotIn predicate on the "sender_email" field.
func SenderEmailNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldSenderEmail, vs...))
}

// SenderEmailGT applies the GT predicate on the "sender_email" field.
func SenderEmailGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldSenderEmail, v))
}

// SenderEmailGTE applies the GTE predicate on the "sender_email" field.
func SenderEmailGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldSenderEmail, v))
}

// SenderEmailLT applies the LT predicate on the "sender_email" field.
func SenderEmailLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldSenderEmail, v))
}

// SenderEmailLTE applies the LTE predicate on the "sender_email" field.
func SenderEmailLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldSenderEmail, v))
}

// SenderEmailContains applies the Contains predicate on the "sender_email" field.
func SenderEmailContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldSenderEmail, v))
}

// SenderEmailHasPrefix applies the HasPrefix predicate on the "sender_email" field.
func SenderEmailHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldSenderEmail, v))
}

// SenderEmailHasSuffix applies the HasSuffix predicate on the "sender_email" field.
func SenderEmailHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldSenderEmail, v))
}

// SenderEmailEqualFold applies the EqualFold predicate on the "sender_email" field.
func SenderEmailEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldSenderEmail, v))
}

// SenderEmailContainsFold applies the ContainsFold predicate on the "sender_email" field.
func SenderEmailContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldSenderEmail, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldSubject, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldBody, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldStatus, vs...))
}

// ReadAtEQ applies the EQ predicate on the "read_at" field.
func ReadAtEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldReadAt, v))
}

// ReadAtNEQ applies the NEQ predicate on the "read_at" field.
func ReadAtNEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldReadAt, v))
}

// ReadAtIn applies the In predicate on the "read_at" field.
func ReadAtIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldReadAt, vs...))
}

// ReadAtNotIn applies the NotIn predicate on the "read_at" field.
func ReadAtNotIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldReadAt, vs...))
}

// ReadAtGT applies the GT predicate on the "read_at" field.
func ReadAtGT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldReadAt, v))
}

// ReadAtGTE applies the GTE predicate on the "read_at" field.
func ReadAtGTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldReadAt, v))
}

// ReadAtLT applies the LT predicate on the "read_at" field.
func ReadAtLT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldReadAt, v))
}

// ReadAtLTE applies the LTE predicate on the "read_at" field.
func ReadAtLTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldReadAt, v))
}

// ReadAtIsNil applies the IsNil predicate on the "read_at" field.
func ReadAtIsNil() predicate.Message {
	return predicate.Message(sql.FieldIsNull(FieldReadAt))
}

// ReadAtNotNil applies the NotNil predicate on the "read_at" field.
func ReadAtNotNil() predicate.Message {
	return predicate.Message(sql.FieldNotNull(FieldReadAt))
}

// ArchivedAtEQ applies the EQ predicate on the "archived_at" field.
func ArchivedAtEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldArchivedAt, v))
}

// ArchivedAtNEQ applies the NEQ predicate on the "archived_at" field.
func ArchivedAtNEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldArchivedAt, v))
}

// ArchivedAtIn applies the In predicate on the "archived_at" field.
func ArchivedAtIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldArchivedAt, vs...))
}

// ArchivedAtNotIn applies the NotIn predicate on the "archived_at" field.
func ArchivedAtNotIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldArchivedAt, vs...))
}

// ArchivedAtGT applies the GT predicate on the "archived_at" field.
func ArchivedAtGT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldArchivedAt, v))
}

// ArchivedAtGTE applies the GTE predicate on the "archived_at" field.
func ArchivedAtGTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldArchivedAt, v))
}

// ArchivedAtLT applies the LT predicate on the "archived_at" field.
func ArchivedAtLT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldArchivedAt, v))
}

// ArchivedAtLTE applies the LTE predicate on the "archived_at" field.
func ArchivedAtLTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldArchivedAt, v))
}

// ArchivedAtIsNil applies the IsNil predicate on the "archived_at" field.
func ArchivedAtIsNil() predicate.Message {
	return predicate.Message(sql.FieldIsNull(FieldArchivedAt))
}

// ArchivedAtNotNil applies the NotNil predicate on the "archived_at" field.
func ArchivedAtNotNil() predicate.Message {
	return predicate.Message(sql.FieldNotNull(FieldArchivedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Message) predicate.Message {
	return predicate.Message(sql.NotPredicates(p))
}
