// Code generated by ent, DO NOT EDIT.

package blogpost

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the blogpost type in the database.
	Label = "blog_post"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldExcerpt holds the string denoting the excerpt field in the database.
	FieldExcerpt = "excerpt"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldCoverImagePlaceholder holds the string denoting the cover_image_placeholder field in the database.
	FieldCoverImagePlaceholder = "coverImagePlaceholder"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFeatured holds the string denoting the featured field in the database.
	FieldFeatured = "featured"
	// FieldPublishDate holds the string denoting the publish_date field in the database.
	FieldPublishDate = "publishDate"
	// FieldReadingTime holds the string denoting the reading_time field in the database.
	FieldReadingTime = "readingTime"
	// FieldSeoTitle holds the string denoting the seo_title field in the database.
	FieldSeoTitle = "seoTitle"
	// FieldSeoDescription holds the string denoting the seo_description field in the database.
	FieldSeoDescription = "seoDescription"
	// FieldAuthorName holds the string denoting the author_name field in the database.
	FieldAuthorName = "authorName"
	// FieldAuthorUserID holds the string denoting the author_user_id field in the database.
	FieldAuthorUserID = "authorUserId"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "createdAt"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updatedAt"
	// EdgeComments holds the string denoting the comments edge name in mutations.
	EdgeComments = "comments"
	// EdgeAuthor holds the string denoting the author edge name in mutations.
	EdgeAuthor = "author"
	// Table holds the table name of the blogpost in the database.
	Table = "blogPost"
	// CommentsTable is the table that holds the comments relation/edge.
	CommentsTable = "blogComment"
	// CommentsInverseTable is the table name for the BlogComment entity.
	// It exists in this package in order to avoid circular dependency with the "blogcomment" package.
	CommentsInverseTable = "blogComment"
	// CommentsColumn is the table column denoting the comments relation/edge.
	CommentsColumn = "blogPostId"
	// AuthorTable is the table that holds the author relation/edge.
	AuthorTable = "blogPost"
	// AuthorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AuthorInverseTable = "user"
	// AuthorColumn is the table column denoting the author relation/edge.
	AuthorColumn = "authorUserId"
)

// Columns holds all SQL columns for blogpost fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldSlug,
	FieldExcerpt,
	FieldContent,
	FieldTags,
	FieldCategory,
	FieldCoverImagePlaceholder,
	FieldStatus,
	FieldFeatured,
	FieldPublishDate,
	FieldReadingTime,
	FieldSeoTitle,
	FieldSeoDescription,
	FieldAuthorName,
	FieldAuthorUserID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// ExcerptValidator is a validator for the "excerpt" field. It is called by the builders before save.
	ExcerptValidator func(string) error
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func(string) error
	// CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	CategoryValidator func(string) error
	// DefaultFeatured holds the default value on creation for the "featured" field.
	DefaultFeatured bool
	// ReadingTimeValidator is a validator for the "reading_time" field. It is called by the builders before save.
	ReadingTimeValidator func(string) error
	// AuthorNameValidator is a validator for the "author_name" field. It is called by the builders before save.
	AuthorNameValidator func(string) error
	// AuthorUserIDValidator is a validator for the "author_user_id" field. It is called by the builders before save.
	AuthorUserIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusDRAFT is the default value of the Status enum.
const DefaultStatus = StatusDRAFT

// Status values.
const (
	StatusDRAFT     Status = "DRAFT"
	StatusPUBLISHED Status = "PUBLISHED"
	StatusARCHIVED  Status = "ARCHIVED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusDRAFT, StatusPUBLISHED, StatusARCHIVED:
		return nil
	default:
		return fmt.Errorf("blogpost: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the BlogPost queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByExcerpt orders the results by the excerpt field.
func ByExcerpt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExcerpt, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByCoverImagePlaceholder orders the results by the cover_image_placeholder field.
func ByCoverImagePlaceholder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoverImagePlaceholder, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFeatured orders the results by the featured field.
func ByFeatured(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeatured, opts...).ToFunc()
}

// ByPublishDate orders the results by the publish_date field.
func ByPublishDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishDate, opts...).ToFunc()
}

// ByReadingTime orders the results by the reading_time field.
func ByReadingTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReadingTime, opts...).ToFunc()
}

// BySeoTitle orders the results by the seo_title field.
func BySeoTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeoTitle, opts...).ToFunc()
}

// BySeoDescription orders the results by the seo_description field.
func BySeoDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeoDescription, opts...).ToFunc()
}

// ByAuthorName orders the results by the author_name field.
func ByAuthorName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorName, opts...).ToFunc()
}

// ByAuthorUserID orders the results by the author_user_id field.
func ByAuthorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorUserID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCommentsCount orders the results by comments count.
func ByCommentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCommentsStep(), opts...)
	}
}

// ByComments orders the results by comments terms.
func ByComments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCommentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAuthorField orders the results by author field.
func ByAuthorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuthorStep(), sql.OrderByField(field, opts...))
	}
}
func newCommentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CommentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CommentsTable, CommentsColumn),
	)
}
func newAuthorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuthorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AuthorTable, AuthorColumn),
	)
}
