// Code generated by ent, DO NOT EDIT.

package blogpost

import (
	"api/internal/infrastructure/persistence/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContainsFold(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldTitle, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldSlug, v))
}

// Excerpt applies equality check predicate on the "excerpt" field. It's identical to ExcerptEQ.
func Excerpt(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldExcerpt, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldContent, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldCategory, v))
}

// CoverImagePlaceholder applies equality check predicate on the "cover_image_placeholder" field. It's identical to CoverImagePlaceholderEQ.
func CoverImagePlaceholder(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldCoverImagePlaceholder, v))
}

// Featured applies equality check predicate on the "featured" field. It's identical to FeaturedEQ.
func Featured(v bool) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldFeatured, v))
}

// PublishDate applies equality check predicate on the "publish_date" field. It's identical to PublishDateEQ.
func PublishDate(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldPublishDate, v))
}

// ReadingTime applies equality check predicate on the "reading_time" field. It's identical to ReadingTimeEQ.
func ReadingTime(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldReadingTime, v))
}

// SeoTitle applies equality check predicate on the "seo_title" field. It's identical to SeoTitleEQ.
func SeoTitle(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldSeoTitle, v))
}

// SeoDescription applies equality check predicate on the "seo_description" field. It's identical to SeoDescriptionEQ.
func SeoDescription(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldSeoDescription, v))
}

// AuthorName applies equality check predicate on the "author_name" field. It's identical to AuthorNameEQ.
func AuthorName(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldAuthorName, v))
}

// AuthorUserID applies equality check predicate on the "author_user_id" field. It's identical to AuthorUserIDEQ.
func AuthorUserID(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldAuthorUserID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldUpdatedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContainsFold(FieldTitle, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContainsFold(FieldSlug, v))
}

// ExcerptEQ applies the EQ predicate on the "excerpt" field.
func ExcerptEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldExcerpt, v))
}

// ExcerptNEQ applies the NEQ predicate on the "excerpt" field.
func ExcerptNEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNEQ(FieldExcerpt, v))
}

// ExcerptIn applies the In predicate on the "excerpt" field.
func ExcerptIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIn(FieldExcerpt, vs...))
}

// ExcerptNotIn applies the NotIn predicate on the "excerpt" field.
func ExcerptNotIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotIn(FieldExcerpt, vs...))
}

// ExcerptGT applies the GT predicate on the "excerpt" field.
func ExcerptGT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGT(FieldExcerpt, v))
}

// ExcerptGTE applies the GTE predicate on the "excerpt" field.
func ExcerptGTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGTE(FieldExcerpt, v))
}

// ExcerptLT applies the LT predicate on the "excerpt" field.
func ExcerptLT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLT(FieldExcerpt, v))
}

// ExcerptLTE applies the LTE predicate on the "excerpt" field.
func ExcerptLTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLTE(FieldExcerpt, v))
}

// ExcerptContains applies the Contains predicate on the "excerpt" field.
func ExcerptContains(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContains(FieldExcerpt, v))
}

// ExcerptHasPrefix applies the HasPrefix predicate on the "excerpt" field.
func ExcerptHasPrefix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasPrefix(FieldExcerpt, v))
}

// ExcerptHasSuffix applies the HasSuffix predicate on the "excerpt" field.
func ExcerptHasSuffix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasSuffix(FieldExcerpt, v))
}

// ExcerptEqualFold applies the EqualFold predicate on the "excerpt" field.
func ExcerptEqualFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEqualFold(FieldExcerpt, v))
}

// ExcerptContainsFold applies the ContainsFold predicate on the "excerpt" field.
func ExcerptContainsFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContainsFold(FieldExcerpt, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContainsFold(FieldContent, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotNull(FieldTags))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContainsFold(FieldCategory, v))
}

// CoverImagePlaceholderEQ applies the EQ predicate on the "cover_image_placeholder" field.
func CoverImagePlaceholderEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldCoverImagePlaceholder, v))
}

// CoverImagePlaceholderNEQ applies the NEQ predicate on the "cover_image_placeholder" field.
func CoverImagePlaceholderNEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNEQ(FieldCoverImagePlaceholder, v))
}

// CoverImagePlaceholderIn applies the In predicate on the "cover_image_placeholder" field.
func CoverImagePlaceholderIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIn(FieldCoverImagePlaceholder, vs...))
}

// CoverImagePlaceholderNotIn applies the NotIn predicate on the "cover_image_placeholder" field.
func CoverImagePlaceholderNotIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotIn(FieldCoverImagePlaceholder, vs...))
}

// CoverImagePlaceholderGT applies the GT predicate on the "cover_image_placeholder" field.
func CoverImagePlaceholderGT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGT(FieldCoverImagePlaceholder, v))
}

// CoverImagePlaceholderGTE applies the GTE predicate on the "cover_image_placeholder" field.
func CoverImagePlaceholderGTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGTE(FieldCoverImagePlaceholder, v))
}

// CoverImagePlaceholderLT applies the LT predicate on the "cover_image_placeholder" field.
func CoverImagePlaceholderLT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLT(FieldCoverImagePlaceholder, v))
}

// CoverImagePlaceholderLTE applies the LTE predicate on the "cover_image_placeholder" field.
func CoverImagePlaceholderLTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLTE(FieldCoverImagePlaceholder, v))
}

// CoverImagePlaceholderContains applies the Contains predicate on the "cover_image_placeholder" field.
func CoverImagePlaceholderContains(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContains(FieldCoverImagePlaceholder, v))
}

// CoverImagePlaceholderHasPrefix applies the HasPrefix predicate on the "cover_image_placeholder" field.
func CoverImagePlaceholderHasPrefix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasPrefix(FieldCoverImagePlaceholder, v))
}

// CoverImagePlaceholderHasSuffix applies the HasSuffix predicate on the "cover_image_placeholder" field.
func CoverImagePlaceholderHasSuffix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasSuffix(FieldCoverImagePlaceholder, v))
}

// CoverImagePlaceholderIsNil applies the IsNil predicate on the "cover_image_placeholder" field.
func CoverImagePlaceholderIsNil() predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIsNull(FieldCoverImagePlaceholder))
}

// CoverImagePlaceholderNotNil applies the NotNil predicate on the "cover_image_placeholder" field.
func CoverImagePlaceholderNotNil() predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotNull(FieldCoverImagePlaceholder))
}

// CoverImagePlaceholderEqualFold applies the EqualFold predicate on the "cover_image_placeholder" field.
func CoverImagePlaceholderEqualFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEqualFold(FieldCoverImagePlaceholder, v))
}

// CoverImagePlaceholderContainsFold applies the ContainsFold predicate on the "cover_image_placeholder" field.
func CoverImagePlaceholderContainsFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContainsFold(FieldCoverImagePlaceholder, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotIn(FieldStatus, vs...))
}

// FeaturedEQ applies the EQ predicate on the "featured" field.
func FeaturedEQ(v bool) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldFeatured, v))
}

// FeaturedNEQ applies the NEQ predicate on the "featured" field.
func FeaturedNEQ(v bool) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNEQ(FieldFeatured, v))
}

// PublishDateEQ applies the EQ predicate on the "publish_date" field.
func PublishDateEQ(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldPublishDate, v))
}

// PublishDateNEQ applies the NEQ predicate on the "publish_date" field.
func PublishDateNEQ(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNEQ(FieldPublishDate, v))
}

// PublishDateIn applies the In predicate on the "publish_date" field.
func PublishDateIn(vs ...time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIn(FieldPublishDate, vs...))
}

// PublishDateNotIn applies the NotIn predicate on the "publish_date" field.
func PublishDateNotIn(vs ...time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotIn(FieldPublishDate, vs...))
}

// PublishDateGT applies the GT predicate on the "publish_date" field.
func PublishDateGT(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGT(FieldPublishDate, v))
}

// PublishDateGTE applies the GTE predicate on the "publish_date" field.
func PublishDateGTE(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGTE(FieldPublishDate, v))
}

// PublishDateLT applies the LT predicate on the "publish_date" field.
func PublishDateLT(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLT(FieldPublishDate, v))
}

// PublishDateLTE applies the LTE predicate on the "publish_date" field.
func PublishDateLTE(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLTE(FieldPublishDate, v))
}

// PublishDateIsNil applies the IsNil predicate on the "publish_date" field.
func PublishDateIsNil() predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIsNull(FieldPublishDate))
}

// PublishDateNotNil applies the NotNil predicate on the "publish_date" field.
func PublishDateNotNil() predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotNull(FieldPublishDate))
}

// ReadingTimeEQ applies the EQ predicate on the "reading_time" field.
func ReadingTimeEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldReadingTime, v))
}

// ReadingTimeNEQ applies the NEQ predicate on the "reading_time" field.
func ReadingTimeNEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNEQ(FieldReadingTime, v))
}

// ReadingTimeIn applies the In predicate on the "reading_time" field.
func ReadingTimeIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIn(FieldReadingTime, vs...))
}

// ReadingTimeNotIn applies the NotIn predicate on the "reading_time" field.
func ReadingTimeNotIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotIn(FieldReadingTime, vs...))
}

// ReadingTimeGT applies the GT predicate on the "reading_time" field.
func ReadingTimeGT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGT(FieldReadingTime, v))
}

// ReadingTimeGTE applies the GTE predicate on the "reading_time" field.
func ReadingTimeGTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGTE(FieldReadingTime, v))
}

// ReadingTimeLT applies the LT predicate on the "reading_time" field.
func ReadingTimeLT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLT(FieldReadingTime, v))
}

// ReadingTimeLTE applies the LTE predicate on the "reading_time" field.
func ReadingTimeLTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLTE(FieldReadingTime, v))
}

// ReadingTimeContains applies the Contains predicate on the "reading_time" field.
func ReadingTimeContains(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContains(FieldReadingTime, v))
}

// ReadingTimeHasPrefix applies the HasPrefix predicate on the "reading_time" field.
func ReadingTimeHasPrefix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasPrefix(FieldReadingTime, v))
}

// ReadingTimeHasSuffix applies the HasSuffix predicate on the "reading_time" field.
func ReadingTimeHasSuffix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasSuffix(FieldReadingTime, v))
}

// ReadingTimeEqualFold applies the EqualFold predicate on the "reading_time" field.
func ReadingTimeEqualFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEqualFold(FieldReadingTime, v))
}

// ReadingTimeContainsFold applies the ContainsFold predicate on the "reading_time" field.
func ReadingTimeContainsFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContainsFold(FieldReadingTime, v))
}

// SeoTitleEQ applies the EQ predicate on the "seo_title" field.
func SeoTitleEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldSeoTitle, v))
}

// SeoTitleNEQ applies the NEQ predicate on the "seo_title" field.
func SeoTitleNEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNEQ(FieldSeoTitle, v))
}

// SeoTitleIn applies the In predicate on the "seo_title" field.
func SeoTitleIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIn(FieldSeoTitle, vs...))
}

// SeoTitleNotIn applies the NotIn predicate on the "seo_title" field.
func SeoTitleNotIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotIn(FieldSeoTitle, vs...))
}

// SeoTitleGT applies the GT predicate on the "seo_title" field.
func SeoTitleGT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGT(FieldSeoTitle, v))
}

// SeoTitleGTE applies the GTE predicate on the "seo_title" field.
func SeoTitleGTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGTE(FieldSeoTitle, v))
}

// SeoTitleLT applies the LT predicate on the "seo_title" field.
func SeoTitleLT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLT(FieldSeoTitle, v))
}

// SeoTitleLTE applies the LTE predicate on the "seo_title" field.
func SeoTitleLTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLTE(FieldSeoTitle, v))
}

// SeoTitleContains applies the Contains predicate on the "seo_title" field.
func SeoTitleContains(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContains(FieldSeoTitle, v))
}

// SeoTitleHasPrefix applies the HasPrefix predicate on the "seo_title" field.
func SeoTitleHasPrefix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasPrefix(FieldSeoTitle, v))
}

// SeoTitleHasSuffix applies the HasSuffix predicate on the "seo_title" field.
func SeoTitleHasSuffix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasSuffix(FieldSeoTitle, v))
}

// SeoTitleIsNil applies the IsNil predicate on the "seo_title" field.
func SeoTitleIsNil() predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIsNull(FieldSeoTitle))
}

// SeoTitleNotNil applies the NotNil predicate on the "seo_title" field.
func SeoTitleNotNil() predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotNull(FieldSeoTitle))
}

// SeoTitleEqualFold applies the EqualFold predicate on the "seo_title" field.
func SeoTitleEqualFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEqualFold(FieldSeoTitle, v))
}

// SeoTitleContainsFold applies the ContainsFold predicate on the "seo_title" field.
func SeoTitleContainsFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContainsFold(FieldSeoTitle, v))
}

// SeoDescriptionEQ applies the EQ predicate on the "seo_description" field.
func SeoDescriptionEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldSeoDescription, v))
}

// SeoDescriptionNEQ applies the NEQ predicate on the "seo_description" field.
func SeoDescriptionNEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNEQ(FieldSeoDescription, v))
}

// SeoDescriptionIn applies the In predicate on the "seo_description" field.
func SeoDescriptionIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIn(FieldSeoDescription, vs...))
}

// SeoDescriptionNotIn applies the NotIn predicate on the "seo_description" field.
func SeoDescriptionNotIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotIn(FieldSeoDescription, vs...))
}

// SeoDescriptionGT applies the GT predicate on the "seo_description" field.
func SeoDescriptionGT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGT(FieldSeoDescription, v))
}

// SeoDescriptionGTE applies the GTE predicate on the "seo_description" field.
func SeoDescriptionGTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGTE(FieldSeoDescription, v))
}

// SeoDescriptionLT applies the LT predicate on the "seo_description" field.
func SeoDescriptionLT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLT(FieldSeoDescription, v))
}

// SeoDescriptionLTE applies the LTE predicate on the "seo_description" field.
func SeoDescriptionLTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLTE(FieldSeoDescription, v))
}

// SeoDescriptionContains applies the Contains predicate on the "seo_description" field.
func SeoDescriptionContains(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContains(FieldSeoDescription, v))
}

// SeoDescriptionHasPrefix applies the HasPrefix predicate on the "seo_description" field.
func SeoDescriptionHasPrefix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasPrefix(FieldSeoDescription, v))
}

// SeoDescriptionHasSuffix applies the HasSuffix predicate on the "seo_description" field.
func SeoDescriptionHasSuffix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasSuffix(FieldSeoDescription, v))
}

// SeoDescriptionIsNil applies the IsNil predicate on the "seo_description" field.
func SeoDescriptionIsNil() predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIsNull(FieldSeoDescription))
}

// SeoDescriptionNotNil applies the NotNil predicate on the "seo_description" field.
func SeoDescriptionNotNil() predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotNull(FieldSeoDescription))
}

// SeoDescriptionEqualFold applies the EqualFold predicate on the "seo_description" field.
func SeoDescriptionEqualFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEqualFold(FieldSeoDescription, v))
}

// SeoDescriptionContainsFold applies the ContainsFold predicate on the "seo_description" field.
func SeoDescriptionContainsFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContainsFold(FieldSeoDescription, v))
}

// AuthorNameEQ applies the EQ predicate on the "author_name" field.
func AuthorNameEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldAuthorName, v))
}

// AuthorNameNEQ applies the NEQ predicate on the "author_name" field.
func AuthorNameNEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNEQ(FieldAuthorName, v))
}

// AuthorNameIn applies the In predicate on the "author_name" field.
func AuthorNameIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIn(FieldAuthorName, vs...))
}

// AuthorNameNotIn applies the NotIn predicate on the "author_name" field.
func AuthorNameNotIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotIn(FieldAuthorName, vs...))
}

// AuthorNameGT applies the GT predicate on the "author_name" field.
func AuthorNameGT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGT(FieldAuthorName, v))
}

// AuthorNameGTE applies the GTE predicate on the "author_name" field.
func AuthorNameGTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGTE(FieldAuthorName, v))
}

// AuthorNameLT applies the LT predicate on the "author_name" field.
func AuthorNameLT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLT(FieldAuthorName, v))
}

// AuthorNameLTE applies the LTE predicate on the "author_name" field.
func AuthorNameLTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLTE(FieldAuthorName, v))
}

// AuthorNameContains applies the Contains predicate on the "author_name" field.
func AuthorNameContains(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContains(FieldAuthorName, v))
}

// AuthorNameHasPrefix applies the HasPrefix predicate on the "author_name" field.
func AuthorNameHasPrefix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasPrefix(FieldAuthorName, v))
}

// AuthorNameHasSuffix applies the HasSuffix predicate on the "author_name" field.
func AuthorNameHasSuffix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasSuffix(FieldAuthorName, v))
}

// AuthorNameEqualFold applies the EqualFold predicate on the "author_name" field.
func AuthorNameEqualFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEqualFold(FieldAuthorName, v))
}

// AuthorNameContainsFold applies the ContainsFold predicate on the "author_name" field.
func AuthorNameContainsFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContainsFold(FieldAuthorName, v))
}

// AuthorUserIDEQ applies the EQ predicate on the "author_user_id" field.
func AuthorUserIDEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldAuthorUserID, v))
}

// AuthorUserIDNEQ applies the NEQ predicate on the "author_user_id" field.
func AuthorUserIDNEQ(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNEQ(FieldAuthorUserID, v))
}

// AuthorUserIDIn applies the In predicate on the "author_user_id" field.
func AuthorUserIDIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIn(FieldAuthorUserID, vs...))
}

// AuthorUserIDNotIn applies the NotIn predicate on the "author_user_id" field.
func AuthorUserIDNotIn(vs ...string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotIn(FieldAuthorUserID, vs...))
}

// AuthorUserIDGT applies the GT predicate on the "author_user_id" field.
func AuthorUserIDGT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGT(FieldAuthorUserID, v))
}

// AuthorUserIDGTE applies the GTE predicate on the "author_user_id" field.
func AuthorUserIDGTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGTE(FieldAuthorUserID, v))
}

// AuthorUserIDLT applies the LT predicate on the "author_user_id" field.
func AuthorUserIDLT(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLT(FieldAuthorUserID, v))
}

// AuthorUserIDLTE applies the LTE predicate on the "author_user_id" field.
func AuthorUserIDLTE(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLTE(FieldAuthorUserID, v))
}

// AuthorUserIDContains applies the Contains predicate on the "author_user_id" field.
func AuthorUserIDContains(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContains(FieldAuthorUserID, v))
}

// AuthorUserIDHasPrefix applies the HasPrefix predicate on the "author_user_id" field.
func AuthorUserIDHasPrefix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasPrefix(FieldAuthorUserID, v))
}

// AuthorUserIDHasSuffix applies the HasSuffix predicate on the "author_user_id" field.
func AuthorUserIDHasSuffix(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldHasSuffix(FieldAuthorUserID, v))
}

// AuthorUserIDEqualFold applies the EqualFold predicate on the "author_user_id" field.
func AuthorUserIDEqualFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEqualFold(FieldAuthorUserID, v))
}

// AuthorUserIDContainsFold applies the ContainsFold predicate on the "author_user_id" field.
func AuthorUserIDContainsFold(v string) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldContainsFold(FieldAuthorUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BlogPost {
	return predicate.BlogPost(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasComments applies the HasEdge predicate on the "comments" edge.
func HasComments() predicate.BlogPost {
	return predicate.BlogPost(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CommentsTable, CommentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommentsWith applies the HasEdge predicate on the "comments" edge with a given conditions (other predicates).
func HasCommentsWith(preds ...predicate.BlogComment) predicate.BlogPost {
	return predicate.BlogPost(func(s *sql.Selector) {
		step := newCommentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAuthor applies the HasEdge predicate on the "author" edge.
func HasAuthor() predicate.BlogPost {
	return predicate.BlogPost(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AuthorTable, AuthorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuthorWith applies the HasEdge predicate on the "author" edge with a given conditions (other predicates).
func HasAuthorWith(preds ...predicate.User) predicate.BlogPost {
	return predicate.BlogPost(func(s *sql.Selector) {
		step := newAuthorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BlogPost) predicate.BlogPost {
	return predicate.BlogPost(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BlogPost) predicate.BlogPost {
	return predicate.BlogPost(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BlogPost) predicate.BlogPost {
	return predicate.BlogPost(sql.NotPredicates(p))
}
