// Code generated by ent, DO NOT EDIT.

package cvdownloadlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the cvdownloadlog type in the database.
	Label = "cv_download_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIPHash holds the string denoting the ip_hash field in the database.
	FieldIPHash = "ipHash"
	// FieldUserAgent holds the string denoting the user_agent field in the database.
	FieldUserAgent = "userAgent"
	// FieldReferrer holds the string denoting the referrer field in the database.
	FieldReferrer = "referrer"
	// FieldDownloadedAt holds the string denoting the downloaded_at field in the database.
	FieldDownloadedAt = "downloadedAt"
	// Table holds the table name of the cvdownloadlog in the database.
	Table = "cvDownloadLog"
)

// Columns holds all SQL columns for cvdownloadlog fields.
var Columns = []string{
	FieldID,
	FieldIPHash,
	FieldUserAgent,
	FieldReferrer,
	FieldDownloadedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IPHashValidator is a validator for the "ip_hash" field. It is called by the builders before save.
	IPHashValidator func(string) error
	// UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	UserAgentValidator func(string) error
	// DefaultReferrer holds the default value on creation for the "referrer" field.
	DefaultReferrer string
	// ReferrerValidator is a validator for the "referrer" field. It is called by the builders before save.
	ReferrerValidator func(string) error
	// DefaultDownloadedAt holds the default value on creation for the "downloaded_at" field.
	DefaultDownloadedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the CVDownloadLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIPHash orders the results by the ip_hash field.
func ByIPHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIPHash, opts...).ToFunc()
}

// ByUserAgent orders the results by the user_agent field.
func ByUserAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserAgent, opts...).ToFunc()
}

// ByReferrer orders the results by the referrer field.
func ByReferrer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferrer, opts...).ToFunc()
}

// ByDownloadedAt orders the results by the downloaded_at field.
func ByDownloadedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloadedAt, opts...).ToFunc()
}
